### ISSUE TITLE
A-bot Speaker

### ISSUE THREAD

**Issue by DW-Studios** [FunkinCrew/Funkin#2587] opened 2024-05-22 14:28 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.3

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://github.com/FunkinCrew/Funkin/assets/126744077/e349332c-77f7-45b4-bed1-ebe66c688368)

**Comment by DW-Studios** [comment] 2024-05-22 14:30
I downloaded the last version of FNF on itch io and the audio visualizer don't react to the music.

**Comment by EnterTheVoid-x86** [comment] 2024-05-22 17:29
This is LITERALLY pinned.

**Comment by JackXson-Real** [comment] 2024-05-22 21:02
Bro did NOT see the pinned issue 💀

**Comment by EliteMasterEric** [comment] 2024-05-22 21:11
Duplicate of #2216

**Closed by EliteMasterEric** 2024-05-22 21:11 UTC
Labels: status: duplicate
