### ISSUE TITLE
Bug Report: BF and GF does their select animations besides Pico and Nene if you immediately select Pico on character select screen.

### ISSUE THREAD

**Issue by Olgu19010** [FunkinCrew/Funkin#3288] opened 2024-09-15 00:04 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![fnf bug](https://github.com/user-attachments/assets/49ab3aa7-931a-49f1-b1a7-57b0f1435986)

In this photo you see what happens if you select Pico immediately on character select screen.

**Comment by GoombarioFan** [comment] 2024-09-15 03:33
Duplicate of #3201

**Comment by EliteMasterEric** [comment] 2024-10-01 14:21
Duplicate

**Closed by EliteMasterEric** 2024-10-01 14:21 UTC
Labels: status: duplicate
