### ISSUE TITLE
Bug Report: Large Offsets Prevent songs from playing

### ISSUE THREAD

**Issue by lando07** [FunkinCrew/Funkin#3644] opened 2024-10-11 03:16 UTC
### Issue Checklist

- [X] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Linux

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

My Bluetooth headphones have a large delay, and that throws the timing of the arrows and the music off from my inputs. When setting the input and visual offset to any value, it throws a Null Object Reference when trying to exit(the offsets save, though). Once restarting the game, any song played enters an infinite loop. My current offsets are +77ms for my input offset and my visual offset is currently at zero. The visual offset does not affect the infinite loop, it only seems to be the input offset

Seems to be apart of bug report #3635 and #3495 but I'm able to reproduce it easily, unintentionally, and intentionally.

### Steps to Reproduce

1. Open the game
2. Change input offset to very large amount(Somewhere above 20ms)
3. Exit(95% chance to encounter a Null Object Reference with a stack trace)
4. Reopen the game
5. Enter any song with the saved offsets
6. The song infinitely loops once the first note plays, and when you try to restart using the "R" key, restart in the pause menu, or even exit the song there's a chance it will throw a Range Error, particularly once you've changed from bf to pico or vice versa.
(I could not get the Null Object Reference to trigger in this video)
https://github.com/user-attachments/assets/f1cd266e-294c-4c51-b694-306b2d70afba

**Comment by AbnormalPoof** [comment] 2024-10-11 03:22
Duplicate of #3380 and #3495

**Comment by lando07** [comment] 2024-10-11 03:23
Yea just noticed that. I'm able to reproduce it and can give more insight.

**Comment by Johnsen290** [comment] 2024-10-11 05:18
> Yea just noticed that. I'm able to reproduce it and can give more insight.

delete this instead, this is already addressed

**Comment by JVNpixels** [comment] 2024-10-11 17:21
Please close this by hitting the purple checkmark button!

**Closed** 2024-10-11 17:50 UTC
Labels: status: duplicate
