### ISSUE TITLE
Bug Report: No longer functions on Debian 12

### ISSUE THREAD

**Issue by ZGStuff** [FunkinCrew/Funkin#2792] opened 2024-06-13 13:42 UTC
## Describe the bug
Due to Debian 12 using glibc 2.36, Funkin' no longer works and throws a 'version glibc_2.38 not found' error when attempting to start the game.
## To Reproduce
Run Funkin' on Debian 12 or older.
## Expected behavior
Funkin' 0.4.0 runs and allows me to play.
## Screenshots/Video
![Screenshot 2024-06-13 7 40 07 AM](https://github.com/FunkinCrew/Funkin/assets/95325264/b8a87435-b3b3-4980-b38c-7d8413318c67)
## Desktop
 - OS:
 Debian 12 "Bookworm" through ChromeOS Linux VM (aka Crostini)
 - Browser
not applicable, using desktop build
 - Version:
 0.4.0

**Comment by NotHyper-474** [comment] 2024-06-13 15:58
Already reported in #2778

For now you can either build the game yourself or use my [builds] (https://github.com/NotHyper-474/Funkin/releases/tag/v0.4.1)

**Comment by EliteMasterEric** [comment] 2024-06-16 04:10
Duplicate of #2778.

**Closed by EliteMasterEric** 2024-06-16 04:10 UTC
Labels: status: duplicate
