### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by OMGcheese997** [FunkinCrew/Funkin#1080] opened 2021-05-12 19:27 UTC
I wrote the following: 
"PS C:\Users\fordo\Downloads\Funkin-master\Funkin-master> lime test windows" in windows powershell.

But then a minute after it said: 

"C:/Users/fordo/Downloads/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/Users/fordo/Downloads/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access
source/PlayState.hx:150: characters 3-39 : Warning : `FlxCamera.defaultCameras` is deprecated, use `FlxG.cameras.setDefaultDrawTarget` instead
C:\Users\fordo\Downloads\Funkin-master\Funkin-master\export\release\windows\obj>setlocal enabledelayedexpansion
Warning: Could not find Visual Studio 2017 VsDevCmd
Missing HXCPP_VARS
Error: Could not automatically setup MSVC"

What does this mean? And how do you fix it? thx.

**Comment by VMGuy23** [comment] 2021-05-12 19:30
Duplicate of #1051

That one isn't solved either but this is a duplicate. I have same issue by the way

**Closed** 2024-05-08 06:59 UTC
Labels: legacy
