### ISSUE TITLE
Bug Report: Linux Desktop Version Dependency Error

### ISSUE THREAD

**Issue by ttheng3810** [FunkinCrew/Funkin#3821] opened 2024-11-02 18:37 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Linux

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

I have downloaded from the official itch.io website and tried to launch the Linux version of Friday Night Funkin but it did not start successfully as expected. Attempting to run the `Funkin` program via terminal returns me the following error messages:

```
./Funkin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./Funkin)
./Funkin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./Funkin)
```

The OS I'm using is Pop!_OS version 22.04. A troubleshooting step I've found online instructs me to update the `libc` package using the command `sudo apt install libc6` but it returns that I'm already running the latest version (which is 2.35 though).

This [site](https://www.reddit.com/r/linux4noobs/comments/1bycyya/running_into_a_version_glibc_238_not_found_error/) says that the error is due to the dependency being too new for my current OS version. If that _is_ the case, I'll appreciate it if the Linux version can be released in a way that can be run by older systems as well.

### Steps to Reproduce

1. Download the Linux release from the itch.io site.
2. Extract the package and run `Funkin`.
3. Observe that the program doesn't load. If it is run through terminal instead, the error messages as previously mentioned can be found.

**Comment by NotHyper-474** [comment] 2024-11-02 18:49
I have [some builds](https://github.com/NotHyper-474/Funkin-Legacy-Linux/releases] in my repository that can run with older GLibC's.

Alternatively you can use Distrobox to make a container with a distro that has GLibC 2.38 or newer to run the game.

Eitherway this is technically a duplicate of https://github.com/FunkinCrew/Funkin/issues/2778.

**Closed** 2024-11-18 23:24 UTC
Labels: status: duplicate
