### ISSUE TITLE
Bug report: Pico can die during Pico doppleganger cutscene

### ISSUE THREAD

**Issue by RawMEATCube** [FunkinCrew/Funkin#3379] opened 2024-09-18 23:33 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - MacOS

### If you are playing on a browser, which one are you using?

None

### Version

v0.5.0

### Context (Provide images, videos, etc.)

If you hit notes during the cutscene where Pico encounters Pico, you will still take damage and you will die. Upon restarting, it will load the song but play the cutscene again without the strum line notes or the hud elements visible.

### Steps to reproduce (or crash logs, errors, etc.)

Enter a week 3 song as Pico and hit the arrow keys (or note keybinds) and continue to hit them until you die.

**Comment by CrusherNotDrip** [comment] 2024-09-19 01:12
Duplicate of #3146

**Comment by EliteMasterEric** [comment] 2024-09-22 04:51
Duplicate

**Closed by EliteMasterEric** 2024-09-22 04:51 UTC
Labels: status: duplicate
