### ISSUE TITLE
Bug Report: Game crashes on week 6 if you press all the buttons on your controller

### ISSUE THREAD

**Issue by Midou36O** [FunkinCrew/Funkin#374] opened 2021-02-07 10:30 UTC
### Web
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [ ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [x] Linux
- [ ] macOS

## What version of the game are you using?
0.2.7
## Have you identified any steps to reproduce the bug?
1.connect controller.
2.choose week 6.
3.when senpai's dialog starts, mash every button (like if you're stuck in Super Smash Bros).
4.game automatically crashes.

## Please describe your issue. Provide extensive detail and images if possibe.
Normally i mash every button to skip senpai's dialog, with arrow keys (on keyboard) it's doable. But on controller it crashes the game. (Actually pressing 1 button at a time doesn't even make senpai progress, you're forced to use the keyboard in order to continue the dialog.)

Can't record because recording and playing freezes my pc sorry (._. ;)

**Comment by devin503** [comment] 2021-02-07 18:43
Duplicate of #365

**Comment by Midou36O** [comment] 2021-02-07 19:19
![image](https://user-images.githubusercontent.com/45198486/107156964-b5febb80-6981-11eb-96c4-d620222b6a4f.png)
true, tried mashing every keyboard button (it's pretty hard) and it happened

**Closed** 2024-05-08 07:05 UTC
Labels: legacy
