### ISSUE TITLE
Bug Report: Chart Editor File => Exit Menubar Item Crash

### ISSUE THREAD

**Issue by Blue2359** [FunkinCrew/Funkin#3200] opened 2024-09-13 15:57 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

The `File => Exit` Menubar context item can crash the game once you click on it;
*BUT*, when you just use the hotkey for this (which is `CTRL+Q`), the game will return to `MainMenuState` like normal.

![image](https://github.com/user-attachments/assets/10036594-9e7c-4b94-9584-e45fd550042e)

## *Proceeds to give the crash error:*
Null Object Reference
  in haxe/ui/containers/menus/Menu.hx#374
  in haxe/ui/containers/menus/Menu.hx#176
  in haxe/ui/util/Timer.hx#10
  in haxe/ui/backend/TimerImpl.hx#17

-------------------
*Additional Info:*
-------------------

Render method: DRAW_TILES

=====================

HXCPP-Immix:
- Memory Used: 452022868 bytes
- Memory Reserved: 514977364 bytes
- Memory Current Pool: 452026708 bytes
- Memory Large Pool: 386977620 bytes
- HXCPP Debugger: Disabled
- HXCPP Exp Generational Mode: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Debug Link: Disabled
- HXCPP Stack Trace: Enabled
- HXCPP Stack Trace Line Numbers: Enabled
- HXCPP Pointer Validation: Enabled
- HXCPP Profiler: Disabled
- HXCPP Local Telemetry: Disabled
- HXCPP C++11: Disabled
- Source Annotation: Disabled

### Steps to reproduce (or crash logs, errors, etc.)

Everything relating to this issue are listed in the description as it is.

**Comment by NotHyper-474** [comment] 2024-09-13 16:45
Ironically enough that's the same issue mentioned here https://github.com/FunkinCrew/Funkin/pull/3060

**Comment by Blue2359** [comment] 2024-09-13 16:58
haha.... whoops...

**Comment by Hundrec** [comment] 2024-09-30 18:49
lol
![image](https://github.com/user-attachments/assets/0a7ffa64-391f-4c8b-a017-aefb3f8a509c)

**Comment by NotHyper-474** [comment] 2024-09-30 18:55
Wuh, I swear it didn't crash for me lol

**Comment by Hundrec** [comment] 2024-09-30 18:55
Whoops, I think this might be caused by https://github.com/FunkinCrew/Funkin/issues/2579 and just happened when I hit Exit

**Comment by NotHyper-474** [comment] 2024-09-30 18:58
Yeah even the error message is the same

**Comment by Hundrec** [comment] 2024-09-30 19:19
Okay, tested again and can confirm this bug is fixed.

**Comment by EliteMasterEric** [comment] 2024-10-01 14:16
Duplicate of #2579 and definitely not fixed in v0.5.1.

**Closed by EliteMasterEric** 2024-10-01 14:16 UTC
Labels: type: major bug, status: resolved

**Comment by NotHyper-474** [comment] 2024-10-01 15:11
Hmm I don't think so, this one seems to have a different cause since only clicking the Exit button caused it.

But that's been resolved anyway so it doesn't really matter.
