### ISSUE TITLE
Bug Report: Several bugs in thorns

### ISSUE THREAD

**Issue by Damianeitor** [FunkinCrew/Funkin#3448] opened 2024-09-24 20:27 UTC
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/1f669d71-cdf3-45a8-8015-67e63f38c8d6

(sorry for the poor quality)
The afterimage of spirit is not in its place and the camera is not the new one from the pixelated levels

**Comment by AbnormalPoof** [comment] 2024-09-24 20:40
Duplicate of #3144

**Closed** 2024-09-24 21:03 UTC
Labels: type: minor bug, status: pending triage
