### ISSUE TITLE
Compiling help:  ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24    294 |       coreAssetRedirect: CORE_FOLDER,       |       ^^^^^^^^^^^^^^^^^       | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

### ISSUE THREAD

**Issue by chicken-nugget1104** [FunkinCrew/Funkin#2471] opened 2024-05-12 01:41 UTC
ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect
      
      WHAT DO I DO TO FIX THIS
      
      im using everything from the develop branch, and i used hmm to install everything
      so what the fluff is happening this wasnt happening earlier!!

**Comment by moxie-coder** [comment] 2024-05-12 04:36
duplicate of #2299

**Closed** 2024-05-12 18:04 UTC
Labels: status: duplicate
