### ISSUE TITLE
Bug Report: [You can hit notes and lose the song while Bot Play is activated]

### ISSUE THREAD

**Issue by Prod-42** [FunkinCrew/Funkin#2700] opened 2024-06-08 09:54 UTC
### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

1. Open the chart editor on any song
2. Open the playtest properties window
3. Activate Bot Play
4. Test the song ( it doesn't matter if it's on minimal mode or normal)
5. Press any note while testing the song with Bot Play On
6. That's all

## Please describe your issue. Provide extensive detail and images if possible.

While testing a song on the chart editor you can still press the notes with BotPlay On, making it possible to get a game over when in my opinion it should not be the case, making the point of using Bot Play kinda useless since u can interfere with its function.

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

https://github.com/FunkinCrew/Funkin/assets/85413903/3a3f34d1-d877-4af9-af75-38edd0cfedd7

https://github.com/FunkinCrew/Funkin/assets/85413903/be62164a-215e-4ac7-a14e-f2a20a63208d

**Comment by Hundrec** [comment] 2024-06-08 16:16
Also reported in #2358 but these videos are very helpful!

I'm not sure if they'll disable inputs during Botplay, but it sounds like a potential solution.

**Comment by EliteMasterEric** [comment] 2024-06-17 02:36
Duplicate of #2358.

**Closed by EliteMasterEric** 2024-06-17 02:36 UTC
Labels: status: duplicate
