### ISSUE TITLE
Bug Report: dad battle pico mix normal and easy difficulty do not have notes

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#3188] opened 2024-09-13 11:06 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

same as title

**Comment by usb-port-2** [comment] 2024-09-13 17:05
not you again sob

**Comment by eXteRadis** [comment] 2024-09-13 18:39
I got the same problem on chrome :/

**Comment by 7oltan** [comment] 2024-09-13 20:22
> not you again sob

hey im being professional STOP (they might hire me tehe)

**Comment by usb-port-2** [comment] 2024-09-14 08:42
> > not you again sob
> 
> hey im being professional STOP (they might hire me tehe)

7oltan callout doc (all they did was mildly annoy frakits)

**Comment by EliteMasterEric** [comment] 2024-09-16 20:36
Closing since this is a duplicate of #3149

**Closed by EliteMasterEric** 2024-09-16 20:36 UTC
Labels: type: minor bug, status: pending triage

**Comment by usb-port-2** [comment] 2024-09-17 10:19
> Closing since this is a duplicate of #3149

actually it isnt since #3149 reported the device as web

**Comment by EliteMasterEric** [comment] 2024-09-18 07:17
The issue is cross-platform anyway so it doesn't matter.
