### ISSUE TITLE
Bug Report: Gameplay stutters on most songs

### ISSUE THREAD

**Issue by Banjoei** [FunkinCrew/Funkin#3613] opened 2024-10-07 20:39 UTC
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

While playing any song on freeplay, the audio will stutter. This causes the notes to bounce incorrectly and causes accidental misses. (File has been compressed to fit the upload limit, but the stutters are still shown)

https://github.com/user-attachments/assets/bea088c6-8884-44c9-8593-213a8f47f88c

### Steps to Reproduce

1. Open the game
2. Select Freeplay
3. Select any song
4. Play the song

**Comment by AbnormalPoof** [comment] 2024-10-07 20:41
Duplicate of #3495.

**Comment by Hundrec** [comment] 2024-10-07 20:51
Please close this issue using the purple checkmark button.
For future reports, be sure to complete the Issue Checklist!

**Closed** 2024-10-07 22:06 UTC
Labels: status: duplicate
