### ISSUE TITLE
Bug Report: "Free Play" crashes game

### ISSUE THREAD

**Issue by VMGuy23** [FunkinCrew/Funkin#1001] opened 2021-05-01 20:03 UTC
Using Edge Dev (Ubuntu 21.04) on self-compiled (Also 21.04, with 20.10 Haxe PPA) game freezes and requires refresh when "Free Play" is clicked.

**Comment by PurpleButNotALight** [comment] 2021-05-02 12:50
Crash log?

**Comment by VMGuy23** [comment] 2021-05-02 13:01
Segmentation fault (core dumped)

**Comment by VMGuy23** [comment] 2021-05-02 13:02
...that's it
But I did notice that the free play list is empty in the game files

**Comment by VMGuy23** [comment] 2021-05-02 13:05
Full log:
`Link: ApplicationMain-debug
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
source/NGio.hx:38: INIT NOLOGIN
source/Discord.hx:12: Discord Client starting...
source/Discord.hx:62: Discord Client initialized
source/Discord.hx:19: Discord Client started.
source/MusicBeatState.hx:25: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/MainMenuState.hx:182: Freeplay Menu Selected
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from FreeplayState::create FreeplayState.hx line 126
Called from FreeplayState::changeSelection FreeplayState.hx line 261
Error : Null Object Reference
`

**Comment by VMGuy23** [comment] 2021-05-02 14:16
Happened after enabling -debug

**Comment by OPNA2608** [comment] 2021-05-03 07:34
Duplicate of #601 / #672. Try #412.

**Comment by Michael82548** [comment] 2021-06-03 23:24
Any reason why #412 isn't merged?

**Closed** 2024-05-08 07:00 UTC
Labels: legacy
