### ISSUE TITLE
Bug Report: DadBattle (Pico Mix) on normal difficulty has no chart

### ISSUE THREAD

**Issue by IntangibleMatter** [FunkinCrew/Funkin#3343] opened 2024-09-17 07:58 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Firefox

### Version

0.5.0

### Context (Provide images, videos, etc.)

I opened the game on Newgrounds, switched to Pico mode, then played Bopbeebo (Pico) normally. I then decided to try DadBattle, which made no indication of issue, but has loaded without any notes. The camera still switches singers, though.

The Console does not indicate any issues.

Due to the fact 0 notes were hit, it's a loss with a score of 0 on the results screen.

https://github.com/user-attachments/assets/6f7c5427-a746-4cdc-81c7-77a5b990d3fa

### Steps to reproduce (or crash logs, errors, etc.)

It is unknown how I caused this issue in the first place, and the logs all appear completely normal. Just a large amount of "Dad/Pico finished animation: Idle" and the occasional camera change.

**Comment by NotHyper-474** [comment] 2024-09-17 08:16
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3149

**Comment by EliteMasterEric** [comment] 2024-09-18 07:18
Duplicate

**Closed by EliteMasterEric** 2024-09-18 07:18 UTC
Labels: status: duplicate
