### ISSUE TITLE
Bug Report: Freeplay doesnt work in funkin-master 

### ISSUE THREAD

**Issue by ghost** [FunkinCrew/Funkin#672] opened 2021-03-29 08:11 UTC
i wanted to make a mod using the source files and i came up with this issue
![image](https://user-images.githubusercontent.com/81555680/112806214-3cc93e00-907f-11eb-8d85-21a7757cd012.png)
i started coding recently and i have no idea how to fix this and all i know is that i didnt cause this issue at all

**Comment by OPNA2608** [comment] 2021-03-29 12:41
Possible duplicate of #601. Try applying #412 as a local patch and see if that fixes your problem.

**Comment by aflacc** [comment] 2021-03-29 22:14
in Freeplaystate.hx the list of weeks to be added, change the number in the lists from week 2 and up down by 1. so it should be that number should be the week number

**Closed** 2024-05-08 07:03 UTC
Labels: legacy
