### ISSUE TITLE
Bug Report: Restarting song

### ISSUE THREAD

**Issue by Webbewwforsure** [FunkinCrew/Funkin#3383] opened 2024-09-19 05:04 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

playable pico

### Context (Provide images, videos, etc.)

so, basically, when a song ends in the pico remixes, it just restarts without the notes, and if you just wait for it to end, it restarts again, happened to me 3 times (bopeebo, south and pico)

### Steps to reproduce (or crash logs, errors, etc.)

enter the song, press esc, and resume

**Comment by AbnormalPoof** [comment] 2024-09-19 05:09
duplicate of #3142

**Comment by Webbewwforsure** [comment] 2024-09-19 05:13
> duplicate of #3142

a, srry

**Comment by Hundrec** [comment] 2024-09-19 07:51
No worries! Please close this issue using the purple button at the bottom of the page.

**Comment by EliteMasterEric** [comment] 2024-09-22 04:50
Duplicate

**Closed by EliteMasterEric** 2024-09-22 04:50 UTC
Labels: status: duplicate
