### ISSUE TITLE
Unable to compile on Linux

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [FunkinCrew/Funkin#2796] opened 2024-06-13 17:40 UTC
I have tried to manually compile the game, and this does not allow me to compile it, I have followed the compilation steps, installing the dependencies and everything

Is something affecting the compilation? I use Haxe version 4.3.2 in case it's worth mentioning.

``` C
quetzalcoutl@quetzal-devuan:/mnt/datos/Documentos/Projects/FNF/Funkin$ haxelib run lime test linux
/mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/hxp/1,2,2/src/hxp/HostPlatform.hx:3: characters 1-7 : Warning : (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`
source/Prebuild.hx:15: Building...
 WARNING /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/flixel-addons/git/flixel/addons/tile/FlxTilemapExt.hx:337: lines 337-427
 
 337 | override public function overlapsWithCallback(object:FlxObject, ?callback:FlxObject->FlxObject->Bool, flipCallbackParams:Bool = false,
   - | [...]
 427 | }
     |
     | overlapsWithCallback is deprecated, use objectOverlapsTiles
 
 ERROR source/funkin/ui/transition/preload/FunkinPreloader.hx:31: character 1
 
  31 | class LogoImage extends BitmapData {}
     | ^
     | Uncaught exception File not found 'art/preloaderArt.png'
 
      -> /usr/share/haxe_20230901120757_a6ac3ae/std/haxe/macro/Context.hx:117: characters 10-39
 
      117 | return load("resolve_path", 1)(file);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/openfl/git/src/openfl/utils/_internal/AssetsMacro.hx:157: characters 16-45
 
      157 | path = Context.resolvePath(filePath);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
       41 | var fields = embedData(":bitmap");
          | ^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/play/stage/ScriptedBopper.hx:8: character 1
 
        8 | class ScriptedBopper extends funkin.play.stage.Bopper implements polymod.hscript.HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedMusicBeatState.hx:8: character 1
 
        8 | class ScriptedMusicBeatState extends funkin.ui.MusicBeatState implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxSubState.hx:8: character 1
 
        8 | class ScriptedFlxSubState extends flixel.FlxSubState implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxRuntimeShader.hx:8: character 1
 
        8 | class ScriptedFlxRuntimeShader extends flixel.addons.display.FlxRuntimeShader implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxSpriteGroup.hx:8: character 1
 
        8 | class ScriptedFlxSpriteGroup extends flixel.group.FlxSpriteGroup.FlxTypedSpriteGroup implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxAtlasSprite.hx:8: character 1
 
        8 | class ScriptedFlxAtlasSprite extends funkin.graphics.adobeanimate.FlxAtlasSprite implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxUIState.hx:8: character 1
 
        8 | class ScriptedFlxUIState extends flixel.addons.ui.FlxUIState implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxSprite.hx:8: character 1
 
        8 | class ScriptedFlxSprite extends flixel.FlxSprite implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFunkinSprite.hx:8: character 1
 
        8 | class ScriptedFunkinSprite extends funkin.graphics.FunkinSprite implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxState.hx:8: character 1
 
        8 | class ScriptedFlxState extends flixel.FlxState implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedFlxTransitionableState.hx:8: character 1
 
        8 | class ScriptedFlxTransitionableState extends flixel.addons.transition.FlxTransitionableState implements HScriptedClass {}
          | ^
          | Called from here
 
      -> /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/polymod/git/polymod/hscript/_internal/HScriptedClassMacro.hx:125: characters 25-34
 
      125 | var builtValue = builder();
          | ^^^^^^^^^
          | Called from here
 
       38 | fields = buildHScriptClass(cls, fields);
          | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
 
      -> source/funkin/modding/base/ScriptedMusicBeatSubState.hx:8: character 1
 
        8 | class ScriptedMusicBeatSubState extends funkin.ui.MusicBeatSubState implements HScriptedClass {}
          | ^
          | Called from here
```

**Comment by NotHyper-474** [comment] 2024-06-13 18:20
Is the "art" folder empty?

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 18:41
@NotHyper-474 I see that part of the error was caused by the "art" folder being missing.

But now this happens:

``` C
quetzalcoutl@quetzal-devuan:/mnt/datos/Documentos/Projects/FNF/Funkin$ haxelib run lime test linux
source/Prebuild.hx:15: Building...
 WARNING  /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/flixel-addons/git/flixel/addons/tile/FlxTilemapExt.hx:337: lines 337-427

 337 |  override public function overlapsWithCallback(object:FlxObject, ?callback:FlxObject->FlxObject->Bool, flipCallbackParams:Bool = false,
   - |    [...]
 427 |  }
     |
     | overlapsWithCallback is deprecated, use objectOverlapsTiles

 ERROR  (unknown position)

     | Type not found : T

```

**Comment by NotHyper-474** [comment] 2024-06-13 18:45
Try reinstalling flixel through `hmm reinstall -f flixel` and compiling the game with `-clean` option

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 18:50
@NotHyper-474 How would I do that by recompiling the game with the -clean option?

```
lime test linux -clean
```

?

**Comment by NotHyper-474** [comment] 2024-06-13 18:51
> @NotHyper-474 How would I do that by recompiling the game with the -clean option?
> 
> ```
> lime test linux -clean
> ```
> 
> ?

Yes, like that

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 18:54
Now this is what happens :|

``` C
quetzalcoutl@quetzal-devuan:/mnt/datos/Documentos/Projects/FNF/Funkin$ haxelib run lime test linux -clean
source/Prebuild.hx:15: Building...
 WARNING  /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | @:enum
     | ^^^^^^
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  /mnt/datos/Documentos/Projects/FNF/Funkin/.haxelib/thx,core/git/src/thx/Weekday.hx:7: characters 1-7

   7 | @:enum
     | ^^^^^^
     | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 INFO  source/funkin/util/Constants.hx:101: characters 41-87

 101 |   public static final GIT_HASH:String = funkin.util.macro.GitCommit.getGitCommitHash();
     |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     | [WARN] Could not determine current git commit; is this a proper Git repository?

 ERROR  /usr/share/haxe_20230901120757_a6ac3ae/std/haxe/io/Input.hx:189: characters 37-42

 189 |     #if neko neko.Lib.rethrow #else throw #end (e);
     |                                     ^^^^^
     | Uncaught exception Eof

      ->  source/funkin/util/macro/GitCommit.hx:23: characters 29-54

       23 |     var commitHash:String = process.stdout.readLine();
          |                             ^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  source/funkin/util/Constants.hx:101: characters 41-87

      101 |   public static final GIT_HASH:String = funkin.util.macro.GitCommit.getGitCommitHash();
          |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here

```

**Comment by NotHyper-474** [comment] 2024-06-13 19:06
@QuetzalcoutlDev How did you clone the repo?

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 19:18
I downloaded the code using the "Download Zip" option from Github

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 19:18
@NotHyper-474 I downloaded the code using the "Download Zip" option from Github

**Comment by NotHyper-474** [comment] 2024-06-13 20:30
@QuetzalcoutlDev Well, that's why. It's preferable to do `git clone <repo-link>` instead.

But you can still setup the ZIP folder you extracted. Just run these commands in this order:

1. `git init .`
2. `git remote add origin https://github.com/FunkinCrew/Funkin.git`
3. `git fetch`
4. `git reset origin/main`
5. `git checkout main`
6. `git submodule update --init --recursive`

Lmk if something went wrong

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 21:28
@NotHyper-474 Apparently it has already started compiling, I will tell you if it works correctly

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 22:02
@NotHyper-474 Again, the compilation keeps failing xD

``` haxe
Error: In file included from ./src/__boot__.cpp:4217:
include/hxcodec/openfl/Video.h:14:10: fatal error: vlc/vlc.h: No existe el fichero o el directorio
   14 | #include "vlc/vlc.h"
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by NotHyper-474** [comment] 2024-06-13 22:07
> @NotHyper-474 Again, the compilation keeps failing xD
> 
> ``` haxe
> Error: In file included from ./src/__boot__.cpp:4217:
> include/hxcodec/openfl/Video.h:14:10: fatal error: vlc/vlc.h: No existe el fichero o el directorio
>    14 | #include "vlc/vlc.h"
>       |          ^~~~~~~~~~~
> compilation terminated.
> ```

Oh, fortunately I've run into that same issue before so I know how to fix it :trollface:

Just install libvlc-dev and libvlccore-dev with your distro's package manager (fr instance, `sudo apt install` for Debian based distros) and it should be fixed.

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 22:56
@NotHyper-474 In the end it did compile, but now when "Segment Fault" is executed :|

I don't think I can do any more XD

**Comment by NotHyper-474** [comment] 2024-06-13 23:19
@QuetzalcoutlDev Oh well XD

But it happens when you open it? And is the error only a segfault or is there something more to it?

**Comment by QuetzalcoutlDev** [comment] 2024-06-13 23:26
@NotHyper-474 After passing the loading screen during game startup, the game closes and gives an error

Where it says "Violación de segmento" it means "Segment Fault"

![imagen](https://github.com/FunkinCrew/Funkin/assets/102568894/fca4dd21-3dd2-4d70-9846-6f8f80b07c7c)

**Comment by NotHyper-474** [comment] 2024-06-14 03:04
> @NotHyper-474 After passing the loading screen during game startup, the game closes and gives an error
> 
> Where it says "Violación de segmento" it means "Segment Fault"
> 
> ![imagen](https://github.com/FunkinCrew/Funkin/assets/102568894/fca4dd21-3dd2-4d70-9846-6f8f80b07c7c)
> 

Odd, does the same thing happen in the Itch.io version?

**Comment by QuetzalcoutlDev** [comment] 2024-06-14 03:18
@NotHyper-474 The version that is in itch.io does not run on my distro (I use Devuan 5) since it lacks GLIBC_2.38, my distro has is GLIBC_2.36

**Comment by NotHyper-474** [comment] 2024-06-14 03:21
> @NotHyper-474 The version that is in itch.io does not run on my distro (I use Devuan 5) since it lacks GLIBC_2.38, my distro has is GLIBC_2.36

I see. Since that's the case could you see if that happens in my build of the game?
It can be found here https://github.com/NotHyper-474/Funkin/releases/tag/v0.4.1

**Comment by QuetzalcoutlDev** [comment] 2024-06-14 03:32
@NotHyper-474 Runs correctly
![imagen](https://github.com/FunkinCrew/Funkin/assets/102568894/e57c3fa4-458b-4cbb-bbbe-8b431d56e562)

**Comment by NotHyper-474** [comment] 2024-06-14 03:35
> @NotHyper-474 Runs correctly
> ![imagen](https://github.com/FunkinCrew/Funkin/assets/102568894/e57c3fa4-458b-4cbb-bbbe-8b431d56e562)
> 

So perhaps it's an issue with FunkinCrew's Lime since it also is using GLibC 2.38. Does running `haxelib run lime` print out an error?

**Comment by QuetzalcoutlDev** [comment] 2024-06-14 03:39
@NotHyper-474 Yes, it's probably a problem with the FunkinCrew file.

But no, during compilation it gives no indication that it will give a "segment fault" error or that it requires GLIBC_2.38

**Comment by Average-FNF-Modder** [comment] 2024-06-14 09:13
> @NotHyper-474 Yes, it's probably a problem with the FunkinCrew file.
> 
> But no, during compilation it gives no indication that it will give a "segment fault" error or that it requires GLIBC_2.38

They should really just get this game a complier with all the issues folks run into.

**Comment by EliteMasterEric** [comment] 2024-07-09 09:06
Have there been any updates on these issues? We have never experienced the issues you are experiencing on any of our CI runners or development machines.

**Comment by moxie-coder** [comment] 2024-07-09 09:08
I could try and compile from native Linux or WSL

**Comment by NotHyper-474** [comment] 2024-07-09 20:50
> Have there been any updates on these issues? We have never experienced the issues you are experiencing on any of our CI runners or development machines.

I went through the trouble of installing the same distro through a VM. Turns out they tried to compile with official Lime instead of FunkinCrew Lime, since I get the same error when using it
```
source/funkin/play/character/CharacterData.hx:186:   Successfully loaded 28 stages.
source/funkin/modding/module/ModuleHandler.hx:27: [MODULEHANDLER] Loading module cache...
source/funkin/modding/module/ModuleHandler.hx:30:   Instantiating 0 modules...
source/funkin/modding/module/ModuleHandler.hx:48: [MODULEHANDLER] Module cache loaded.
source/funkin/InitState.hx:181: Parsing game data took: 44.9999999999999 ms
source/funkin/PlayerSettings.hx:97: loading player settings for id: 1
source/funkin/PlayerSettings.hx:122: Loading default keyboard control scheme
source/funkin/InitState.hx:260: Command line args: { args => [-livereload], chart => { shouldLoadChart => false, chartPath => null } }
source/Main.hx:125: hxcpp_debug_server is disabled! This build does not support debugging.
source/funkin/Conductor.hx:538: Done mapping time changes: [SongTimeChange(0ms,102bpm)]
Segmentation fault
```

Well, not like FunkinCrew Lime is any better xD
```
Called from lime._internal.backend.native.NativeCFFI::boot lime/_internal/backend/native/NativeCFFI.hx line 359
Called from cpp.Prime::_loadPrime /opt/haxe/std/cpp/Prime.hx line 35
Error : Could not load module lime@lime_application_create__prime
```

In this case, running `lime` generally yields this
```
_/\\\\\\______________________________________________
_\////\\\______________________________________________
_____\/\\\_____/\\\_____________________________________
______\/\\\____\///_____/\\\\\__/\\\\\_______/\\\\\\\\___
_______\/\\\_____/\\\__/\\\///\\\\\///\\\___/\\\/////\\\__
________\/\\\____\/\\\_\/\\\_\//\\\__\/\\\__/\\\\\\\\\\\___
_________\/\\\____\/\\\_\/\\\__\/\\\__\/\\\_\//\\///////____
________/\\\\\\\\\_\/\\\_\/\\\__\/\\\__\/\\\__\//\\\\\\\\\\__
________\/////////__\///__\///___\///___\///____\//////////___

Lime Command-Line Tools (8.0.2)
Use lime setup to configure platforms or lime help for more commands
Called from ? line 1
Called from /opt/haxe/std/neko/_std/sys/thread/Thread.hx line 63
Called from /opt/haxe/std/sys/thread/EventLoop.hx line 183
Called from /opt/haxe/std/haxe/MainLoop.hx line 172
Called from lime/system/System.hx line 271
Called from a C function
Called from /opt/haxe/std/neko/Lib.hx line 43
Uncaught exception - load.c(237) : Failed to load library : /path/to/funkin/.haxelib/lime/git//ndll/Linux64/lime.ndll (/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /path/to/funkin/.haxelib/lime/git//ndll/Linux64/lime.ndll))
```
Generally this is fixed by rebuilding Lime itself through `lime rebuild PLATFORM`

It's related to the issue I mentioned on #2778

**Comment by EliteMasterEric** [comment] 2024-10-05 18:00
Issue was a mix of not reading the directions properly (didn't use hmm to install Haxelibs) and a duplicate of #2778.

**Closed** 2024-10-05 18:01 UTC
Labels: type: compilation help, status: resolved
