### ISSUE TITLE
Bug Report: I beat a song I have modded into the game and it gave me a rating on the random button

### ISSUE THREAD

**Issue by Willio2000** [FunkinCrew/Funkin#2809] opened 2024-06-15 03:06 UTC
## Describe the bug
I beat a song that I had modded into the game and it gave me a rating on the random button in the freeplay menu

## To Reproduce
I am not entirely sure how it could be easily reproduced, there's a possibility that it might just be my computer. I will put my mod here, it usually breaks after you beat it once or twice. make sure you beat your previous score on it or else the bug will never occur
[slimecicle.zip](https://github.com/user-attachments/files/15845457/slimecicle.zip)

## Expected behavior
it is supposed to give the rating to the song I was just playing.

## Screenshots/Video
![aaaaa](https://github.com/FunkinCrew/Funkin/assets/65547044/7b5de0a5-9d02-4db9-a78d-0b2f2278fb11)

## Desktop
 - OS:
Windows 10
 - Browser
N/A (I am using the build) (but i use chrome)
 - Version:
0.4.0

## Additional context
Sometimes, when playing the erect remix of my song, it would instead play the normal variation with no charting. So that might also have something to do with it. Another thing to note, Nightmare mode worked completely fine but the normal erect difficulty was where the issues arose. I dont think this is an issue with my mod as I did not add any script files, and also I have checked my metadata files many times and compared them to the vanilla ones.

**Comment by Willio2000** [comment] 2024-06-15 03:12
i have just noticed that there is a new version, ill see if the issue persists on the newer version

**Comment by Willio2000** [comment] 2024-06-15 03:29
something else ive noticed, after restarting the game, the random button no longer has the rating, and the song i got the rating on now has the correct rating.

**Comment by NotHyper-474** [comment] 2024-06-15 04:03
> something else ive noticed, after restarting the game, the random button no longer has the rating, and the song i got the rating on now has the correct rating.

I think it could be that you accidentally tried to scroll through the songs and triggered the same bug from #2676

**Comment by EliteMasterEric** [comment] 2024-06-16 04:18
I reproduced this but only as a duplicate of #2676

**Closed by EliteMasterEric** 2024-06-16 04:18 UTC
Labels: type: minor bug, status: duplicate

**Comment by Willio2000** [comment] 2024-06-20 02:36
that would make sense
