### ISSUE TITLE
Input Offsets Crash on First Start-up

### ISSUE THREAD

**Issue by Blue2359** [FunkinCrew/Funkin#3095] opened 2024-08-07 01:05 UTC
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Other (Specify below)

### Version

0.4.1

### Context (Provide screenshots or videos of the crash happening)

There is a note style/spritesheet crash that can be triggered by going to the "Input Offsets" screen, which is located in the Options Menu as a sub-option.

If you enter this screen **without** loading any song, you'll *possibly* be met with the crash and the error message.

I haven't tested this on a downloadable build yet, only the NG version of the game.
I am using the [Brave browser](https://brave.com/), and I'm also on the [Linux Ubuntu](https://ubuntu.com/) distro if that may help.

I'm guessing this crash happens because the game doesn't properly load the note styles/spritesheet files on the initial start-up of the game; and instead loads them when you're first entering a song mayhaps..?

### Steps to reproduce

1. Enter the game on the [NG Build](https://www.newgrounds.com/portal/view/770371),
2. Go to Options > "Input Offsets";
Do this **without** entering any song,
3. You should be greeted with a note style/spritesheet crash.

![image](https://github.com/user-attachments/assets/325eac68-7b6b-456f-a75e-d5b5e45329da)

### Crash logs (can be found in the logs folder where Funkin.exe is)

Can't, since I'm using the Web build of the game.

**Comment by NotHyper-474** [comment] 2024-08-07 04:04
Already reported on #2078

**Comment by Blue2359** [comment] 2024-08-07 04:12
Ah, whoopsies! Thought I had checked everywhere already, guess not! 😅

**Comment by EliteMasterEric** [comment] 2024-09-22 16:15
Duplicate of #2208

**Closed by EliteMasterEric** 2024-09-22 16:15 UTC
Labels: status: duplicate
