### ISSUE TITLE
The cutscenes are very nice but when you die you would usually want to skip through them. However, if i do it too fast the game just crashes completely and i lose any progress i made. Not sure what causes this but fix pls

### ISSUE THREAD

**Issue by RoseGalax** [FunkinCrew/Funkin#347] opened 2021-02-03 20:04 UTC
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [x] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by regulad** [comment] 2021-02-03 22:12
Duplicate of #328.

**Closed** 2024-05-08 07:05 UTC
Labels: legacy
