### ISSUE TITLE
Bug Report: Small lags in all songs

### ISSUE THREAD

**Issue by LeandroBarbie** [FunkinCrew/Funkin#3700] opened 2024-10-14 01:56 UTC
### Issue Checklist

- [x] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

Just making it clear, my computer is good. It is a Ryzen 5 4600g with an RX6650XT and 32GB RAM.

No matter what the song I am in, there are always some lags (plural) throughout the music, always happening at random times. It could be some reading error, but even when I carry the whole music, the game still lag. For example, I play a song and die at the end, when reborn, the game will still lag.

Enjoying to say that Friday Night Funkin never runs very well on my devices. In the past update, for example, the animation of "New Character Unlocked: Pico" was strictly lined. Was it this game to be that heavy?

### Steps to Reproduce

Start and play any músic.

**Comment by AbnormalPoof** [comment] 2024-10-14 02:01
If the songs are stuttering, then this is a duplicate of:
- https://github.com/FunkinCrew/Funkin/issues/3380
- https://github.com/FunkinCrew/Funkin/issues/3495
- https://github.com/FunkinCrew/Funkin/issues/3667

**Comment by LeandroBarbie** [comment] 2024-10-14 03:01
> If the songs are stuttering, then this is a duplicate of:
> 
> * [Setting Visual Offsets to causes the song to repeatedly skip ("Swing Mode") #3380](https://github.com/FunkinCrew/Funkin/issues/3380)
> * [Unknown issue is causing gamplay to skip, or desync with the song, resulting in gameplay stutter, lag, etc #3495](https://github.com/FunkinCrew/Funkin/issues/3495)
> * [Bug Report: Game still stutters even after 0.5.2 has released #3667](https://github.com/FunkinCrew/Funkin/issues/3667)

Really? Well, at least I know the problem is not on my part. I sent a video of my problem just to make sure it's the same error, is he? I thank you for the answer.

https://github.com/user-attachments/assets/299c8ff5-cbdd-4422-a3d8-1d02e5161d6c

**Comment by Hundrec** [comment] 2024-10-15 21:45
Yes, this is the same issue as the ones above. You may close this issue and contribute to the existing discussions.

**Closed** 2024-10-15 22:23 UTC
Labels: status: duplicate
