### ISSUE TITLE
Bug Report: Mods don't load at all in 0.5.2

### ISSUE THREAD

**Issue by Prebloxx** [FunkinCrew/Funkin#3717] opened 2024-10-16 17:48 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

So I created a simple mod for testing (replacing assets) but it dosen't load at all, I have used the modding guide and I can't compile the github source code because git keeps failing.

### Steps to Reproduce

1. Create a mod
2. Replace assets

**Comment by NotHyper-474** [comment] 2024-10-16 17:54
Since you're unable to debug it if you send/link to your mod maybe someone else could debug it for you.

**Comment by AbnormalPoof** [comment] 2024-10-16 17:54
Make sure `api_version` is set to `0.5.0` in `_polymod_meta.json`

**Comment by NotHyper-474** [comment] 2024-10-16 17:56
> Make sure `api_version` is set to `0.5.0` in `_polymod_meta.json`

Considering https://github.com/FunkinCrew/Funkin/issues/3660#issuecomment-2417374388 I think they've already done that.

**Comment by Prebloxx** [comment] 2024-10-16 18:18
> Since you're unable to debug it if you send/link to your mod maybe someone else could debug it for you.

alr hold on

**Comment by Prebloxx** [comment] 2024-10-16 18:27
> Since you're unable to debug it if you send/link to your mod maybe someone else could debug it for you.

https://drive.google.com/drive/folders/19DPMMEyE-gq7fm-RFRcWlWNz0iexEfKd?usp=sharing

**Comment by NotHyper-474** [comment] 2024-10-16 18:39
Seems like it's trying to load a dependency mod that doesn't exist and is failing
```json
"dependencies": {
      "modA": "1.0.0"
    },
"optionalDependencies": {
      "modB": "1.3.2"
    },
```

If you remove the `"modA": "1.0.0"` line it should be good to go. Might as well remove this whole section if you don't plan to depend on other mods

**Comment by Prebloxx** [comment] 2024-10-16 18:42
> Seems like it's trying to load a dependency mod that doesn't exist and is failing
> 
> ```json
> "dependencies": {
>       "modA": "1.0.0"
>     },
> "optionalDependencies": {
>       "modB": "1.3.2"
>     },
> ```
> 
> If you remove the `"modA": "1.0.0"` line it should be good to go. Might as well remove this entire section if you don't plan to depend on other mods

ohh alr, tysm!

**Comment by AbnormalPoof** [comment] 2024-10-16 18:44
> Seems like it's trying to load a dependency mod that doesn't exist and is failing
> 
> ```json
> "dependencies": {
>       "modA": "1.0.0"
>     },
> "optionalDependencies": {
>       "modB": "1.3.2"
>     },
> ```
> 
> If you remove the `"modA": "1.0.0"` line it should be good to go. Might as well remove this entire section if you don't plan to depend on other mods

Something to note here is that ***every*** mod will be disabled if the dependency thing fails, not just the mod with the non-existent dependency.

**Comment by MAZ12211** [comment] 2024-10-17 14:06
**_Every_** mod? That's annoying and might need a separate issue

**Comment by AbnormalPoof** [comment] 2024-10-17 14:16
This is actually intended behavior in Polymod, there's this flag when passing `init()`:
![Screenshot 2024-10-17 at 9 15 08 AM](https://github.com/user-attachments/assets/ce17110f-4700-4a00-b82c-10a8bd039f8a)
Funkin' doesn't touch this flag when initializing Polymod, so it's disabled.

**Comment by NotHyper-474** [comment] 2024-10-17 14:28
Since it's optional I wonder if there's any downside to enabling it.

**Comment by MAZ12211** [comment] 2024-10-17 14:34
> This is actually intended behavior in Polymod, there's this flag when passing `init()`: ![Screenshot 2024-10-17 at 9 15 08 AM](https://private-user-images.githubusercontent.com/86753001/377504656-ce17110f-4700-4a00-b82c-10a8bd039f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNzU3NDAsIm5iZiI6MTcyOTE3NTQ0MCwicGF0aCI6Ii84Njc1MzAwMS8zNzc1MDQ2NTYtY2UxNzExMGYtNDcwMC00YTAwLWI4MmMtMTBhOGJkMDM5ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDE0MzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwN2Q4MjFkYWQyZWYxYzFkYzMyNTYwNzJkOWFkY2M0YzBjYzA3Y2Y4OGJiMWE0Zjc4YjVlZjhiNWE0NzlmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0qE3MW2zps5ZJQZR-HanH0QhDyp4iYHncHMpBFPZiKQ) Funkin' doesn't touch this flag when initializing Polymod, so it's disabled.

I thought from the documentation it meant that if let's say `modA` doesn't have dependencies, that mod will stop loading in the game until you have it. Not for all mods.

**Comment by 7oltan** [comment] 2024-10-24 17:46
can you close this issue

**Closed** 2024-10-25 00:56 UTC
Labels: type: minor bug, status: pending triage
