### ISSUE TITLE
The cutscene's volume and the music volume are diffrent

### ISSUE THREAD

**Issue by NickMineBoom** [FunkinCrew/Funkin#2526] opened 2024-05-16 13:46 UTC
Every time i play FNF i have it on the lowest volume and the music when i'm playing the levels its at a decent volume but for some reason every cutscene(From the Weekend 1) its almost muted....I have to turn up the volume and then put it back down just to hear the sounds in the cutscenes..Is this a problem for everyone?(itch.io version)

**Comment by JackXson-Real** [comment] 2024-05-16 18:55
Nah bro why did you select compiling help 😭😭

**Comment by EliteMasterEric** [comment] 2024-05-18 18:14
Duplicate of #2410

**Closed by EliteMasterEric** 2024-05-18 18:14 UTC
Labels: status: duplicate

**Comment by NickMineBoom** [comment] 2024-05-18 18:37
> Nah bro why did you select compiling help 😭😭

missclicked..i was cooked
