### ISSUE TITLE
Bug Report: Freeplay Song Select Off Grid Error (High)

### ISSUE THREAD

**Issue by Cringertech** [FunkinCrew/Funkin#3314] opened 2024-09-16 00:16 UTC
### Issue Checklist

- [x] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

Version 0.5.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/df82c901-d429-4b66-9e2c-b41a075d184f)
![image](https://github.com/user-attachments/assets/f06cd4c9-ddd3-40d9-b7d6-6bdae32b90f6)
![image](https://github.com/user-attachments/assets/d59b74e0-881b-453e-8ca9-cca376d2134b)

### Steps to reproduce (or crash logs, errors, etc.)

I don't remember how to redo the bug, and I'm not sure if this only occurs for High or for any of the other songs.

**Comment by SwiftRasin** [comment] 2024-09-16 00:43
this happened for me too. 
![Untitled](https://github.com/user-attachments/assets/dceab51e-6fa7-4056-bf17-65d0ca0ccd08)
i just reproduced this by interrupting (constantly focusing and unfocusing) the song beaten animation after completing a song for the first time. It only really happens if you're trying to do it intentionally.

**Comment by Hundrec** [comment] 2024-09-18 07:55
Also reported in #3239

**Comment by EliteMasterEric** [comment] 2024-09-18 08:10
Duplicate of #3239

**Closed by EliteMasterEric** 2024-09-18 08:10 UTC
Labels: status: duplicate
