### ISSUE TITLE
Crash Report: ERROR: There is no asset library with ID of "weekend1"

### ISSUE THREAD

**Issue by qkoime19** [FunkinCrew/Funkin#3471] opened 2024-09-27 16:52 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

Other (Specify below)

### Version

the latest version of brave browser

### Context (Provide screenshots or videos of the crash happening)

Hello there, when i wanted to download the latest version of fnf i extract the game on my desktop and the game crashes with this  error:
![Екранна снимка 2024-09-22 195336](https://github.com/user-attachments/assets/c5fcbeab-ab0c-4979-a0c1-e88ddcd97f01)
and then i try on my ssecond disk and the game opens fine but after a song it crashes and a new errors shows up saying it cannot find the score... help?

### Steps to reproduce

i dont know what this is 

### Crash logs (can be found in the logs folder where Funkin.exe is)

didnt make one

**Comment by NotHyper-474** [comment] 2024-09-27 16:56
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3277

**Comment by EliteMasterEric** [comment] 2024-09-28 15:14
Duplicate

**Closed by EliteMasterEric** 2024-09-28 15:14 UTC
Labels: status: duplicate
