### ISSUE TITLE
Bug Report: Pressing the arrow keys and dying during the Week 3 Pico Mixes cutscene breaks and crashes the game

### ISSUE THREAD

**Issue by Darkness8374939** [FunkinCrew/Funkin#3272] opened 2024-09-14 18:31 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Pressing the arrow keys and dying during the Week 3 Pick Pico Mixes cutscene bugs the characters and crashes the game.
![Screenshot (4)](https://github.com/user-attachments/assets/34f5567c-182b-4e0d-b732-54949b5ccd79)

Link to full videos of the bug:
https://www.youtube.com/watch?v=wjUxHiSTmOw

https://www.youtube.com/watch?v=itHy8G49awo

### Steps to reproduce (or crash logs, errors, etc.)

Press multiple arrow keys, until you die during the Week 3 Pico Mixes Cutscene.
Press the Retry button in the death screen.

**Comment by EliteMasterEric** [comment] 2024-09-16 20:45
Duplicate of #3146

**Closed by EliteMasterEric** 2024-09-16 20:45 UTC
Labels: status: duplicate
