### ISSUE TITLE
Bug Report: Save reset to default after two launches

### ISSUE THREAD

**Issue by hiimjasmine00** [FunkinCrew/Funkin#2656] opened 2024-06-06 16:05 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [ ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
- Go to options
- Change the options
- Close the game
- Play the game again
- Close the game again
- Open the game
- Save is reset to default

## Please describe your issue. Provide extensive detail and images if possible.
- When you play the game twice, and open the game back up, options are not saved. This is quite the annoyance for me, a DFJK player.
- Not to mention, all of my scores are reset as well, which is also an annoyance.

**Comment by NotHyper-474** [comment] 2024-06-06 18:39
Seems to be a duplicate of https://github.com/FunkinCrew/Funkin/issues/2287

**Closed** 2024-06-07 13:41 UTC
Labels: status: duplicate
