### ISSUE TITLE
Bug Report: Game crash when playing Stress 

### ISSUE THREAD

**Issue by Rorriis** [FunkinCrew/Funkin#2506] opened 2024-05-14 17:11 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows
- [ ] Mac
- [X] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2, with the hxCodex fix to build

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Select Stress from freeplay, wait like a couple of seconds and then it crashes

## Please describe your issue. Provide extensive detail and images if possible.
Not much to say really, heres the terminal log
```
Called from flixel.effects.FlxFlicker.flickerProgress (flixel/effects/FlxFlicker.hx line 171)
Called from flixel.util.FlxTimer.onLoopFinished (flixel/util/FlxTimer.hx line 205)
Called from flixel.util.FlxTimerManager.update (flixel/util/FlxTimer.hx line 295)
Called from flixel.FlxGame.update (flixel/FlxGame.hx line 747)
Called from flixel.FlxGame.step (flixel/FlxGame.hx line 679)
Called from flixel.FlxGame.onEnterFrame (flixel/FlxGame.hx line 558)
Called from openfl.events.EventDispatcher.__dispatchEvent (openfl/events/EventDispatcher.hx line 402)
Called from openfl.display.DisplayObject.__dispatch (openfl/display/DisplayObject.hx line 1399)
Null Object Reference
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 558
Called from flixel.FlxGame::step flixel/FlxGame.hx line 679
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.util.FlxTimerManager::update flixel/util/FlxTimer.hx line 295
Called from flixel.util.FlxTimer::onLoopFinished flixel/util/FlxTimer.hx line 205
Called from flixel.effects.FlxFlicker::flickerProgress flixel/effects/FlxFlicker.hx line 171
Error : Null Object Reference
[eero@eero-90rc009kmw funkin]$
```

**Comment by NotHyper-474** [comment] 2024-05-14 20:05
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2345, it's not specific to Linux

**Comment by Eerorri** [comment] 2024-05-14 20:47
Oh, OK

**Closed by Eerorri** 2024-05-14 20:47 UTC
Labels: status: duplicate
