### ISSUE TITLE
Bug Report: [DadBattle Erect shows up even when the difficulty is lowered]

### ISSUE THREAD

**Issue by hihun8072** [FunkinCrew/Funkin#2691] opened 2024-06-08 06:36 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.4.0 

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Enter the FreePlay screen and change the difficulty to Hard.
![screenshot-2024-06-08-15-31-01](https://github.com/FunkinCrew/Funkin/assets/121847215/a44e77a9-1f3a-4912-8ff2-a03a9df3c21c)

## Please describe your issue. Provide extensive detail and images if possible.
If you change the difficulty to Hard on the FreePlay screen, it will still say DadBattle Erect.

**Comment by Hundrec** [comment] 2024-06-08 07:50
This bug was reported and responded to in #2678 and #2685

**Comment by ninjamuffin99** [comment] 2024-06-09 16:20
closing and marking as duplicate of #2685 !!! also thank you to @Hundrec for also mentioning the original issue! 

will be fixed in 0.4.1 patch!

**Closed** 2024-06-09 16:19 UTC
Labels: status: duplicate
