### ISSUE TITLE
Bug Report: [Pressing Input Offsets on the NG version breaks the game]

### ISSUE THREAD

**Issue by ROBlNET13** [FunkinCrew/Funkin#2233] opened 2024-05-01 18:23 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x ] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3.0 PROTOTYPE

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
On the main menu, go into options and then press on Input Offsets and then the game breaks and shows up a prompt with some error information.
## Please describe your issue. Provide extensive detail and images if possible.
It fully softlocks the game and brings up a prompt with a bunch of error stuff
![chrome_QNbDBBxm2k](https://github.com/FunkinCrew/Funkin/assets/116967343/b1037917-91ed-4c69-9563-f9816c17b053)
![chrome_gpj2kM93qr](https://github.com/FunkinCrew/Funkin/assets/116967343/0c1375c2-fcb6-452f-b5ee-1b51a9632682)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting
Funkin.js:279 [Violation] Permissions policy violation: accelerometer is not allowed in this document.
Funkin.js:308710 Uncaught Could not load spritesheet for note style: funkin
﻿

**Comment by EliteMasterEric** [comment] 2024-09-22 16:15
Duplicate of #2208

**Closed by EliteMasterEric** 2024-09-22 16:15 UTC
Labels: status: duplicate
