### ISSUE TITLE
Crash Report: Crash when loading a song without the currently selected variation

### ISSUE THREAD

**Issue by Hundrec** [FunkinCrew/Funkin#3763] opened 2024-10-25 06:56 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description

In the chart editor, selecting a song under the Create From Song section loads the song in the variation and difficulty you're currently charting. If the song you're trying to load doesn't have the variation/difficulty you're currently charting, the game crashes.

https://github.com/user-attachments/assets/610a01bd-b84f-420c-b1a8-211f6eed6569

### Steps to Reproduce

1. Open the chart editor
2. Select a song that has an Erect variation
3. Change the difficulty to Erect/Nightmare
4. Select a new song that doesn't have an Erect variation
5. Crash!

### Crash logs

[crash-2024-10-24-23-50-42.log](https://github.com/user-attachments/files/17517438/crash-2024-10-24-23-50-42.log)

**Most importantly:** [lime.utils.Assets] ERROR: There is no BINARY asset with an ID of "songs:assets/songs/2hot/Inst-erect.ogg"

**Comment by NotHyper-474** [comment] 2024-10-25 13:10
Duplicate of #2411 and #2468

I can't believe you of all people would make a duplicate issue... (jk)

**Comment by JustKolosaki** [comment] 2024-10-25 14:27
I should probs also check what's up with the debug menu text not being centered hmmm

**Comment by Hundrec** [comment] 2024-10-25 18:07
> Duplicate of #2411 and #2468
> 
> I can't believe you of all people would make a duplicate issue... (jk)

Haha, I went on a late night bug reporting spree and knew this would happen!

**Closed** 2024-10-25 18:07 UTC
Labels: status: duplicate
