### ISSUE TITLE
Bug Report: instead of characters i only see black squares

### ISSUE THREAD

**Issue by hellourcomputerhasvirus** [FunkinCrew/Funkin#1190] opened 2021-05-26 22:47 UTC
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by VMGuy23** [comment] 2021-05-27 17:15
RAM issue. Please close, not a bug

**Comment by NotHyper-474** [comment] 2021-05-31 23:46
Might be lack of a good amount of RAM or lack of a good amount of GPU dedicated Video RAM

**Comment by VMGuy23** [comment] 2021-06-01 09:23
That's what I said above.

**Comment by NotHyper-474** [comment] 2021-06-02 21:09
Just adding the GPU part here

**Comment by hellourcomputerhasvirus** [comment] 2021-06-04 13:02
btw im playing in my browser

**Comment by VMGuy23** [comment] 2021-06-04 13:06
Hi - This is a problem with your computer. This isn't an issue with the game. Please close this issue as we cannot fix it.

**Closed** 2024-05-08 06:58 UTC
Labels: legacy
