### ISSUE TITLE
Crash Report: End Week 1 -  Restarting Song Or Restart when dying makes game crash 

### ISSUE THREAD

**Issue by dylanforcegaming** [FunkinCrew/Funkin#3737] opened 2024-10-19 20:18 UTC
### Issue Checklist

- [x] I have properly named my issue
- [x] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.2

### Description

When i play and die or restart, the philly script has a bug and quits the game
https://github.com/user-attachments/assets/b927b1ef-6442-4a8f-a647-cf1e20456194

### Steps to Reproduce

open 
End week 1 (I used hard)
die or restart song
'Crash'

### Crash logs

all the same
[crash-2024-10-19-15-55-33.log](https://github.com/user-attachments/files/17447258/crash-2024-10-19-15-55-33.log)
[crash-2024-10-19-15-54-31.log](https://github.com/user-attachments/files/17447259/crash-2024-10-19-15-54-31.log)
[crash-2024-10-19-15-52-39.log](https://github.com/user-attachments/files/17447260/crash-2024-10-19-15-52-39.log)
[crash-2024-10-19-15-51-35.log](https://github.com/user-attachments/files/17447261/crash-2024-10-19-15-51-35.log)
[crash-2024-10-19-15-49-38.log](https://github.com/user-attachments/files/17447262/crash-2024-10-19-15-49-38.log)
[crash-2024-10-19-15-35-50.log](https://github.com/user-attachments/files/17447263/crash-2024-10-19-15-35-50.log)

**Comment by NotHyper-474** [comment] 2024-10-19 20:32
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3499

**Comment by dylanforcegaming** [comment] 2024-10-19 20:57
the restarting bug is not in this

**Comment by AbnormalPoof** [comment] 2024-10-20 03:34
Restarting from the Game Over screen is still restarting the song.

**Closed** 2024-10-20 18:08 UTC
Labels: status: duplicate
