### ISSUE TITLE
Entering and Exiting Freeplay

### ISSUE THREAD

**Issue by DaWreker** [FunkinCrew/Funkin#173] opened 2021-01-10 02:36 UTC
While entering and exiting freeplay mode, the last song highlighted will continue playing, including enemy and player lyrics. Probably intended, but thought I'd mention it.

https://user-images.githubusercontent.com/77217961/104112932-7d0bf200-52c2-11eb-83b7-1c737381fb08.mp4

**Comment by gedehari** [comment] 2021-01-10 03:35
Haha this is completely intentional. I even made a fix so that the music will continue the fade in. You can close this now.

**Comment by DaWreker** [comment] 2021-01-10 03:45
I thought the 2.5 changelog stated that they had changed this?

**Comment by DaWreker** [comment] 2021-01-10 03:49
Got this quote from changelog: "IDK i think backing out of song menu should play main menu songs again hehe". Not sure if I'm misreading that or what. Note that I don't even know how to compile the code in a manner similar to Python, because I don't work with Java.

**Comment by gedehari** [comment] 2021-01-10 03:56
Think I remember the developer saying that it's intentional, so I added the fix. I forgot where the issue is. @ninjamuffin99 , is this actually intentional? If not, I will reverse it and add the fix.

**Comment by ninjamuffin99** [comment] 2021-01-15 04:43
it was like semi intention, if its fixed, oh well, if its not fixed ALSO OH WELL LOL!

**Comment by gedehari** [comment] 2021-01-15 05:42
In my opinion it is better to keep it that way, kinda like a SSBU audio vault or osu! where the music keeps playing on the menu.

**Closed** 2024-05-08 07:08 UTC
Labels: legacy
