### ISSUE TITLE
Bug Report: bug in song selection in freeplay

### ISSUE THREAD

**Issue by ImNot4ntony** [FunkinCrew/Funkin#3304] opened 2024-09-15 12:25 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (Playable pico Update)

### Context (Provide images, videos, etc.)

If you play a song before entering the character selector the sprite will bug and change position

https://github.com/user-attachments/assets/7cc7ed4d-c32c-4e81-b3f2-458a8cb70bc4

### Steps to reproduce (or crash logs, errors, etc.)

enter a song before unlocking pico

**Comment by Hundrec** [comment] 2024-09-18 07:54
Also reported in #3239

**Comment by EliteMasterEric** [comment] 2024-09-18 08:13
Duplicate of #3239

**Closed by EliteMasterEric** 2024-09-18 08:13 UTC
Labels: status: duplicate
