### ISSUE TITLE
Bug Report: Long song names on results go down a bit.

### ISSUE THREAD

**Issue by BStasik** [FunkinCrew/Funkin#2756] opened 2024-06-11 19:55 UTC
## Describe the bug
When the name of any song is long enough it goes down a bit.

## To Reproduce
No special actions needed.

## Expected behavior
It should be placed at the same level as difficulty and clear %.

## Screenshots/Video
![image](https://github.com/FunkinCrew/Funkin/assets/172075123/3c9d3250-fc87-4280-963c-b4dd5efdd9e6)

## Desktop
 - OS:
Windows 10
 - Browser
Downloaded from itch.io
 - Version:
0.4.0

## Additional context
No.

**Comment by EliteMasterEric** [comment] 2024-06-12 17:42
Duplicate of #2365

**Closed by EliteMasterEric** 2024-06-12 17:42 UTC
Labels: status: duplicate
