### ISSUE TITLE
Bug Report: Incorrect CLEARED % and ranking on freeplay

### ISSUE THREAD

**Issue by objShaggy** [FunkinCrew/Funkin#2664] opened 2024-06-07 16:37 UTC
- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

Version 0.4

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Get 26 goods or more on a song of choice and still P rank it.

## Please describe your issue. Provide extensive detail and images if possible.

Despite the rank screen saying I got 100% and me having a P rank freeplay says I only have 99%.
After leaving freeplay my P rank turned into an E rank.

![Screenshot 2024-06-07 183106](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/599383cf-e77e-467d-bc77-8ee749b55b07/14b8c06b-241a-44c5-b642-c09704f18c78?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi81OTkzODNjZi1lNzdlLTQ2N2QtYmM3Ny04ZWU3NDliNTViMDcvMTRiOGMwNmItMjQxYS00NGM1LWI2NDItYzA5NzA0ZjE4Yzc4IiwiaWF0IjoxNzE3NzgwMzI1LCJleHAiOjMzMjg4MzQwMzI1fQ.O6FJlTZf4J36MKdR38ZcMhmG5fxlDBiUNJ7I9ceA0OY)

**Comment by M7theguy** [comment] 2024-06-08 14:58
I think the reason why it does that is because it only saves the score (with its rank) with the highest points. (In my opinion, this should be changes to save both the highest score and the highest rank that was achieved in a song)

**Comment by EliteMasterEric** [comment] 2024-06-11 05:04
Confirmed and reproduced. Would flag as high priority but our GitHub labels suck rn.

This happened because, based on the number of Sicks and Goods you got, your previous Excellent had more points than your newest score, despite having a worse rank.

This is set to be fixed in v0.4.1.

**Comment by squidgegame** [comment] 2024-06-11 14:23
> Confirmed and reproduced. Would flag as high priority but our GitHub labels suck rn.
> 
> This happened because, based on the number of Sicks and Goods you got, your previous Excellent had more points than your newest score, despite having a worse rank.
> 
> This is set to be fixed in v0.4.1.
---
oof sorry, i checked for duplicate threads / issues but i missed this one before making my bug report
would it be more helpful for me to delete it or should i just leave it as is?

**Comment by EliteMasterEric** [comment] 2024-06-12 20:05
Fixed in v0.4.1

**Closed by EliteMasterEric** 2024-06-12 20:05 UTC
Labels: bug
