### ISSUE TITLE
2 picos?

### ISSUE THREAD

**Issue by MatejMakesStuff** [FunkinCrew/Funkin#3305] opened 2024-09-15 14:10 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

[Itch.io](http://Itch.io) (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

so i was playing as pico and you know when pico finds himself like a clone? yeah well you can still hit arrows and you can get blueballed then when you retry pico multiplies! and if you press z to skip the cutscene the game crashes.

![Screenshot 2024-09-15 160956](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/8e2cb1a2-3bef-4edd-9ab9-1c2556f3ab9d/52a4a51c-245a-474d-aab8-7426f305f7b0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi84ZTJjYjFhMi0zYmVmLTRlZGQtOWFiOS0xYzI1NTZmM2FiOWQvNTJhNGE1MWMtMjQ1YS00NzRkLWFhYjgtNzQyNmYzMDVmN2IwIiwiaWF0IjoxNzI2NTExOTMxLCJleHAiOjMzMjk3MDcxOTMxfQ.4-J2nOGJF_TZzuLxmZiQnysj_RlD39OviqvRE-HeWzU)

### Steps to reproduce (or crash logs, errors, etc.)

*No response*

**Comment by ImNot4ntony** [comment] 2024-09-15 14:25
* pico learned the cloning skill *

**Comment by mll-enh** [comment] 2024-09-15 16:01
woah three picos
my brain is exploding

**Comment by KernelTech11** [comment] 2024-09-15 16:38
now pico hás 2 twins!!!!

**Comment by MatejMakesStuff** [comment] 2024-09-15 20:22
> * pico learned the cloning skill *

he sure did lol

**Comment by Hundrec** [comment] 2024-09-18 07:42
Duplicate of #3146

**Comment by EliteMasterEric** [comment] 2024-09-18 08:05
Duplicate

**Closed by EliteMasterEric** 2024-09-18 08:05 UTC
Labels: status: duplicate
