### ISSUE TITLE
Bug Report: pico pmix cutscene sprites still have the pencil tool on them from flash cs4

### ISSUE THREAD

**Issue by SussyNooby** [FunkinCrew/Funkin#3406] opened 2024-09-21 07:22 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.50

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/8b11ac43-a040-4128-b2c5-3c3f5d8bd4f6)
![image](https://github.com/user-attachments/assets/a5b02f92-0762-4643-a5ab-dd8591f4658e)

### Steps to reproduce (or crash logs, errors, etc.)

idk what reproduce means but i think its like suggestions to get it fixed so um just remove the pencil tool in the sprites its really bugging me out

**Comment by Hundrec** [comment] 2024-09-21 07:54
This issue was reported in #3216

**Comment by EliteMasterEric** [comment] 2024-09-21 09:34
Duplicate of #3116.

**Closed by EliteMasterEric** 2024-09-21 09:34 UTC
Labels: status: duplicate
