### ISSUE TITLE
Bug Report: Text for a couple Erect remixes displayed weirdly after very specific conditions

### ISSUE THREAD

**Issue by Jaunteru** [FunkinCrew/Funkin#2682] opened 2024-06-07 23:55 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [x] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
After beating "Blammed" in Hard difficulty (possibly the other regular difficulties too), then going up to "Philly Nice", and switching to the Erect Remix of the latter song, the titles for both "Satin Panties Erect" and "Thorns Erect" will show as if compressed to a third of their normal length. I am unaware if other songs provoke this issue, but it only happens when switching from "Philly Nice" to "Philly Nice Erect." This occurs for both the itch.io version and the Newgrounds version, as specified in the first section.

## Please describe your issue. Provide extensive detail and images if possible.
As previously mentioned, The text for both those Erect Remixes shows weirdly and compressed, specifically when switching from Philly Nice to the Erect variant. Switching between other remixes seems to not cause the issue. Going back to the selection menu for story mode/freeplay/etc., and then back to freeplay, does not seem to fix it.

https://youtu.be/PB_mbMShlSc (unlisted video demonstration 1)

https://youtu.be/S1G5y6a-HL4 (unlisted video demonstration 2)

**Comment by Hundrec** [comment] 2024-06-08 00:07
Cam replied to #2659 saying that they're aware of this issue

Good to know it's reproducible!

**Comment by Jaunteru** [comment] 2024-06-08 00:16
Despite checking I completely missed that this was reported earlier. My bad! I'll leave it up in case the video demonstration is of any help

**Comment by EliteMasterEric** [comment] 2024-06-17 02:52
Duplicate of #2659.

**Closed by EliteMasterEric** 2024-06-17 02:52 UTC
Labels: status: duplicate
