### ISSUE TITLE
Crash Report: crash in character selection screen

### ISSUE THREAD

**Issue by ImNot4ntony** [FunkinCrew/Funkin#3303] opened 2024-09-15 12:22 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (Playable pico Update)

### Context (Provide screenshots or videos of the crash happening)

If you select BF before unlocking Pico, the game simply won't know what to do.

additional suggestion: do not force pico to be playable once you enter the update, in the next patch make it necessary to play week 3 before
![Captura de pantalla (2161)](https://github.com/user-attachments/assets/4eef66a0-63a6-4328-aff0-b611aa2f86a3)

### Steps to reproduce

enter the game and select A bf BEFORE pico is unlocked

### Crash logs (can be found in the logs folder where Funkin.exe is)

[crash-2024-09-15-06-04-47.log](https://github.com/user-attachments/files/17005746/crash-2024-09-15-06-04-47.log)

**Comment by MrMooey** [comment] 2024-09-16 03:20
duplicate of #3156

**Comment by EliteMasterEric** [comment] 2024-09-18 08:13
Duplicate

**Closed by EliteMasterEric** 2024-09-18 08:13 UTC
Labels: status: duplicate
