### ISSUE TITLE
Bug Report: Switching character slots really fast in the character select screen will make the actual character not appear

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#3423] opened 2024-09-21 19:26 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/04109169-cbe4-41e6-b6b0-437c2b283151

I thought this was only for switching rows at first, but this also works when you switch columns. If you switch from BF to pico really fast like that, only Nene will appear. 

### Steps to reproduce (or crash logs, errors, etc.)

Switch from one slot in the character select to the next and back really fast.

**Comment by Hundrec** [comment] 2024-09-22 00:48
Also reported in #3193

**Comment by EliteMasterEric** [comment] 2024-09-22 03:17
Duplicate of #3193

**Closed by EliteMasterEric** 2024-09-22 03:17 UTC
Labels: type: minor bug, status: pending triage
