### ISSUE TITLE
Bug Report: Video Cutscenes don't work with mods folder

### ISSUE THREAD

**Issue by shyllis** [FunkinCrew/Funkin#2449] opened 2024-05-11 03:25 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Trying to play a video with using mods folder asset will always result a black screen.

## Please describe your issue. Provide extensive detail and images if possible.
We tried to put the mp4 video into all libraries and even tried to use getPath(), it just doesnt work if its in mods/mymod/ folder

**Comment by shyllis** [comment] 2024-05-13 14:16
They do work, but for some reason I have to type whole directory like "mods/mymod/vids/videoName.mp4", because Paths. doesn't see that

**Comment by AbnormalPoof** [comment] 2024-07-30 07:05
[FunkinCrew/hxCodec#5](https://github.com/FunkinCrew/hxCodec/pull/5) fixes this, along with #2639 I think?

As a temporary solution, OpenFL Assets has a `getPath()` function that returns the full path of an asset. Import `openfl.utils.Assets` and modify the Video Cutscene code as such:

`Assets.getPath(Paths.videos('myVideo'));` (Note that Paths.videos() expects the MP4 to be in `mods/My Mod/videos/videos`.)

**Comment by AbnormalPoof** [comment] 2024-10-02 16:29
Looking at this issue now, I’m pretty sure this is a duplicate of #2446.

**Closed** 2024-10-11 02:25 UTC
Labels: mods, status: bug reproduced
