### ISSUE TITLE
Bug Report: Slower And Cetern Songs Show Up While There Not Supposed 2.

### ISSUE THREAD

**Issue by CatGamer99** [FunkinCrew/Funkin#3740] opened 2024-10-20 03:22 UTC
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

When, I Complete/Quit The Erect Songs. Non Erect Songs Show Up For Example Like "Monster". And, Also It Feels More Laggier Then 0.5.0.

![D0A54DC1-B6A1-44D6-AAB1-FD4F91F15B8E](https://github.com/user-attachments/assets/3eae2dfb-6981-4072-8a13-a33132854d68)

**Comment by AbnormalPoof** [comment] 2024-10-20 03:33
Duplicate of #3514.

**Comment by Hundrec** [comment] 2024-10-20 20:36
> Potential duplicates:
> 
> * [[Bug Report:  #3722](https://github.com/FunkinCrew/Funkin/issues/3722)] Bug Report:  (77.86%)
> * [[Bug Report: intentional or no? #3712](https://github.com/FunkinCrew/Funkin/issues/3712)] Bug Report: intentional or no? (62.86%)

The duplicate duplicate report is wild

**Comment by Hundrec** [comment] 2024-10-30 21:15
Please close this issue, since it's a duplicate of another report.
You can do so by pressing the purple or gray button under the comment box.

**Closed** 2024-10-30 21:18 UTC
Labels: type: minor bug, status: pending triage, potential duplicate
