### ISSUE TITLE
Bug Report: Nene's A-Bot speaker doesn't react to the music

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#2216] opened 2024-05-01 03:14 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [X] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
v0.3 prototype

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
it didn't work on one attempt, and it didn't work again

## Please describe your issue. Provide extensive detail and images if possible.

![image](https://github.com/FunkinCrew/Funkin/assets/73907153/d171cd7a-aa5f-408b-988e-fdd8f5a94ce5)

**Comment by SilverT4** [comment] 2024-05-01 03:46
A video may work better here. I recorded this same thing occurring just now:

https://github.com/FunkinCrew/Funkin/assets/41199354/0dadba6e-2ba6-43a5-ae04-cf42c5b0b8e1

The current version _is_ a prototype, so not everything will work as expected. It's possible this is just a bug with the prototype and the next version will fix it.

**Comment by EliteMasterEric** [comment] 2024-05-08 06:42
Issue is confirmed and being worked on.

**Comment by NotStampyC** [comment] 2024-05-12 08:25
well yea its a newgrounds exclusive

**Comment by NotStampyC** [comment] 2024-05-12 08:25
no shit it dont work

**Comment by Johferson** [comment] 2024-05-15 10:30
is it fixed now? couldn't really see it because i am busy for my upcoming tests

**Comment by nebulazorua** [comment] 2024-05-15 12:53
> well yea its a newgrounds exclusive

no its not its on itch.io

**Comment by biomseed** [comment] 2024-05-15 22:48
> is it fixed now? couldn't really see it because i am busy for my upcoming tests

not yet but they don't know why it's happening

**Comment by NukeThief** [comment] 2024-05-18 16:38
someone on PE discord managed to get it working somehow. i couldn't find the message again. but it's possible.

**Comment by NotHyper-474** [comment] 2024-05-20 18:40
Looking through the code it appears it was intentionally left out in other platforms due to a problem that causes a crash. This doesn't happen in Web version tho since they use a different approach.

**Comment by Skiawm91** [comment] 2024-05-25 13:53
https://drive.google.com/file/d/1P5TarL4JJMbuSw5EVlP0VQKb9497ebN6/view?usp=drive_link
i build " funkin.vis branch: useGrig " Version, now worked.

**Comment by AbnormalPoof** [comment] 2024-06-01 02:26
useGrig does indeed make the visualizer work! However, performance takes a hit... along with the fact that (I think) another A-Bot visualizer gets created on song restart, leading to major FPS drops if you restart enough times. Though, I'm sure these are issues that can be ironed out eventually.

(I can't post a video because the file size is large.)

**Comment by biomseed** [comment] 2024-06-01 15:50
> (I can't post a video because the file size is large.)

Use 8mb.video. It opened my eyes.

**Comment by BaremetalFlesh** [comment] 2024-06-06 16:16
> #### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
> ### If you are playing the game in a browser, what site are you playing it from?
> 
>     * [ ]  [Newgrounds](https://www.newgrounds.com/portal/view/770371)
> 
>     * [x]  [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
> 
>     * * [x]  Windows
> 
>     * * [ ]  Mac
> 
>     * * [ ]  Linux
> 
> 
> ### If you are playing the game in a browser, what browser are you using?
> 
>     * [ ]  Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
> 
>     * [ ]  Firefox
> 
>     * [ ]  Safari
> 
> 
> ## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
> 
> v0.3 prototype
> ## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
> 
> it didn't work on one attempt, and it didn't work again
> ## Please describe your issue. Provide extensive detail and images if possible.
> 
> ![image](https://private-user-images.githubusercontent.com/73907153/327039561-d171cd7a-aa5f-408b-988e-fdd8f5a94ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTA4MTUsIm5iZiI6MTcxNzY5MDUxNSwicGF0aCI6Ii83MzkwNzE1My8zMjcwMzk1NjEtZDE3MWNkN2EtYWE1Zi00MDhiLTk4OGUtZmRkOGY1YTk0Y2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE2MTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTJmMDI5MDVlYjMxNmIxOTU4NmZkZWQxM2FhNmZkYjgxMGVlNjFmMGRkMTRhMzlkNmVlYjE5OTU1MmM4MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._PmWOaO7HozuMnJhWQ0302_CFSNhoBFc_SQtST5VF1o)
> ## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

I'm running it on Arch Linux through wine and the A-bot doesn't work for me.

**Comment by BaremetalFlesh** [comment] 2024-06-06 16:22
I'm gonna start trying to fix it in a few minutes, hopefully it will get merged!

**Comment by AbnormalPoof** [comment] 2024-06-07 03:08
[FunkinCrew/funkVis#5](https://github.com/FunkinCrew/funkVis/pull/5) has been merged! A-Bot has been fixed in the new content update that just released.

**Comment by EliteMasterEric** [comment] 2024-06-07 03:52
Resolved in v0.4.0.

**Closed by EliteMasterEric** 2024-06-07 03:52 UTC
Labels: bug
