### ISSUE TITLE
Bug Report: videoCutscene doesnt work on mods

### ISSUE THREAD

**Issue by 7oltan** [FunkinCrew/Funkin#3456] opened 2024-09-25 18:21 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

the videoCutscene checks for the path but i dont think that works with polymod
i tried adding the video to the main folder and it worked so its 100% a path thing

**Comment by AbnormalPoof** [comment] 2024-09-25 19:18
Duplicate of #2446 and #2449

**Comment by 7oltan** [comment] 2024-09-25 19:56
> Duplicate of #2446 and #2449

sigh, i see you everywhere

**Closed** 2024-09-25 19:56 UTC
Labels: status: duplicate
