### ISSUE TITLE
Bug Report: The music keeps looping after i finish it

### ISSUE THREAD

**Issue by meianove99** [FunkinCrew/Funkin#3295] opened 2024-09-15 05:25 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

When i finished Dadbattle (pico ver.) the music kept looping without the notes and the level wouldn't end and proceed to the results screen

**Comment by AbnormalPoof** [comment] 2024-09-15 05:38
duplicate of #3142

**Comment by EliteMasterEric** [comment] 2024-09-15 06:32
Duplicate

**Closed by EliteMasterEric** 2024-09-15 06:32 UTC
Labels: type: minor bug, status: pending triage
