### ISSUE TITLE
Bug Report: Girlfriend and Boyfriend decided to go on vacation

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#3535] opened 2024-10-02 11:57 UTC
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

When you switch between boyfriend and pico very fast, bf and gf just dissapear (same thing can happen with pico and nene)
![image](https://github.com/user-attachments/assets/27a20819-d9bc-4b12-b752-3b56fb493c01)
![image](https://github.com/user-attachments/assets/78646ae1-510f-4b92-a413-34d90e97be7d)
and extra
![image](https://github.com/user-attachments/assets/43cb28e4-ba79-412d-b26a-d99bb4fa16aa)
![Zrzut ekranu 2024-10-02 142859](https://github.com/user-attachments/assets/fcb34185-91e8-4fec-b43d-bb2ad7a3eaaf)

### Steps to Reproduce

1. Open the game
2. go to character select 
3. switch really fast between pico and bf

**Comment by GoombarioFan** [comment] 2024-10-02 12:29
Seems to be the same as #3302, which is currently closed, but should definitely be reopened.

**Comment by AbnormalPoof** [comment] 2024-10-02 16:50
Duplicate of #3302 + already fixed in #3457

**Closed** 2024-10-04 03:00 UTC
Labels: type: minor bug, status: pending triage
