### ISSUE TITLE
Bug Report: Looped Song

### ISSUE THREAD

**Issue by Tabiba172** [FunkinCrew/Funkin#3255] opened 2024-09-14 08:16 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I don’t know why this could be happening, but it can happen on any song

https://github.com/user-attachments/assets/ff3ffbf7-278d-44cd-a1ad-574a481bf778

https://github.com/user-attachments/assets/5cb3bf8e-6673-46e0-8d95-243fd990b215

**Comment by AbnormalPoof** [comment] 2024-09-14 14:22
duplicate of #3142

**Closed** 2024-10-05 13:54 UTC
Labels: status: duplicate
