### ISSUE TITLE
Bug Report: No inputs registered when any note is bound to LT or RT

### ISSUE THREAD

**Issue by objShaggy** [FunkinCrew/Funkin#2538] opened 2024-05-17 20:55 UTC
### If you are playing the game in a browser, what site are you playing it from?
I am not playing the game in a browser, I am playing the windows version.

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
Version 0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Bind any of the note inputs to LT or RT

## Please describe your issue. Provide extensive detail and images if possible.
When any note inputs are bound to either LT or RT the game does not react to the inputs, despite the options menu letting me bind LT or RT to any of the note inputs.
The controller I use is an Xbox One controller if that information helps.

**Comment by EliteMasterEric** [comment] 2024-06-17 02:28
Duplicate of #2346 .

**Closed by EliteMasterEric** 2024-06-17 02:28 UTC
Labels: status: duplicate
