### ISSUE TITLE
M.I.L.F and Winter Horrorland are on erect difficulty

### ISSUE THREAD

**Issue by Stompyyyy** [FunkinCrew/Funkin#3599] opened 2024-10-06 10:22 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

When you switch to the erect difficulty, M.I.L.F and Winter Horrorland show up. The only way you can get them out of the erect difficulty is by changing the difficulty
![buggy](https://github.com/user-attachments/assets/f43b0879-e2a7-4279-82b5-c31b82615124)

### Steps to Reproduce

1. Switch to erect difficulty

**Comment by Hundrec** [comment] 2024-10-06 10:41
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3514

**Comment by Stompyyyy** [comment] 2024-10-06 10:45
> Duplicate of #3514

oops sorry looks like i cant delete the issue

**Comment by Hundrec** [comment] 2024-10-06 10:46
No worries, you can close it using the purple checkmark button!

**Closed** 2024-10-06 10:47 UTC
Labels: status: duplicate
