### ISSUE TITLE
Bug Report: mousescroll allows you to rank another song

### ISSUE THREAD

**Issue by phych22** [FunkinCrew/Funkin#2770] opened 2024-06-12 21:45 UTC
so, i was playing tutorial trying to p rank it, i did, but instead, i used mousescroll and p ranked stress instead of tutorial, i expected tutorial, but was not expecting to p rank stress, its not that major of a bug, but could be used to fabricate p ranks, thus for competitive fnf, you could do the easy songs, and scroll to p rank a hard song, and still have the p rank for that said song.

**Comment by NotHyper-474** [comment] 2024-06-12 21:53
Duplicate of #2676

**Comment by EliteMasterEric** [comment] 2024-06-16 04:18
Duplicate of #2676

**Closed by EliteMasterEric** 2024-06-16 04:18 UTC
Labels: bug
