### ISSUE TITLE
Crash Report: The game crashes when i quit chart editor

### ISSUE THREAD

**Issue by daniyusk** [FunkinCrew/Funkin#3226] opened 2024-09-13 21:42 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0.0

### Context (Provide screenshots or videos of the crash happening)

Ok, I click the exit button and... boom! The game crashed.

![image](https://github.com/user-attachments/assets/8e669155-17c2-43e4-b9ce-d8003174646f)

### Steps to reproduce

Click exit button in chart editor, lol

### Crash logs (can be found in the logs folder where Funkin.exe is)

[crash-2024-09-13-18-39-23.log](https://github.com/user-attachments/files/16999610/crash-2024-09-13-18-39-23.log)

**Comment by Blue2359** [comment] 2024-09-14 14:46
This is a duplicate of my issue refernenced at #3200

**Closed** 2024-09-18 20:24 UTC
Labels: status: duplicate
