### ISSUE TITLE
Some Pico songs at random will repeat infinitely when the song is done

### ISSUE THREAD

**Issue by squeeenoodle** [FunkinCrew/Funkin#3516] opened 2024-10-01 13:58 UTC
### Issue Checklist

- [X] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.50

### Description (include any images, videos, errors, or crash logs)

Self explanatory.

### Steps to Reproduce

1. Play any Pico mix song
2. Pray

**Comment by AbnormalPoof** [comment] 2024-10-01 14:00
Duplicate of #3142

**Comment by EliteMasterEric** [comment] 2024-10-01 14:10
Duplicate

**Closed by EliteMasterEric** 2024-10-01 14:10 UTC
Labels: status: duplicate
