### ISSUE TITLE
Bug Report: The Christmas version of girlfriend in Friday night Funkin every time I try to use her in the game she keeps on freezing it o tried your phantom arcade one too and it did the same thing

### ISSUE THREAD

**Issue by LolGacchaGay** [FunkinCrew/Funkin#333] opened 2021-02-03 05:35 UTC
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [x] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [x] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [x] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS

**Comment by regulad** [comment] 2021-02-03 15:42
Duplicate of #279. This issue can safely be closed.

**Closed** 2024-05-08 07:06 UTC
Labels: legacy
