### ISSUE TITLE
Bug Report: You can now play as Pico after completing any week

### ISSUE THREAD

**Issue by embedded-p** [FunkinCrew/Funkin#3808] opened 2024-10-30 16:41 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Compiled from GitHub Source Code

### Browser

None

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

https://github.com/user-attachments/assets/ef86ed46-ad75-4dd2-8306-abaf50b12c2c
![you-can-now-play-as-luigi-v0-xrt6j7hmbfjc1](https://github.com/user-attachments/assets/5e58a7dd-cb02-4363-837d-f69e62bafd33)

### Steps to Reproduce

See for yourself, i have just completed Week 2 on Normal difficulty.

**Comment by moxie-coder** [comment] 2024-10-30 16:46
![unacceptable-knight](https://github.com/user-attachments/assets/5cf1a16c-ab0d-40a0-94bd-09a8b0f7d09a)

**Comment by AbnormalPoof** [comment] 2024-10-30 17:49
Not a bug, you have to beat Weekend 1 to unlock him, not just any week.

**Comment by embedded-p** [comment] 2024-10-30 18:33
> Not a bug, you have to beat Weekend 1 to unlock him, not just any week.

but i did on Easy difficulty

**Comment by Hundrec** [comment] 2024-10-30 21:10
Can you elaborate? 
Are you saying you beat Weekend 1 on Easy and didn't unlock Pico?

**Comment by Blue2359** [comment] 2024-10-31 13:44
> > Not a bug, you have to beat Weekend 1 to unlock him, not just any week.
> 
> But i did on Easy difficulty, after that it began to have an issue.

You said that you beat Week 2, not Weekend 1, which is the reason to him not unlocking..?

**Comment by embedded-p** [comment] 2024-10-31 14:42
> Can you elaborate? Are you saying you beat Weekend 1 on Easy and didn't unlock Pico?

I did, but i'll explain once more: As i COMPLETED the Weekend 1, the "You can now play as [that character i referred to]" text appeared for the first time, but now, the game began to "remind" me of the character i've just opened as i completed any week beside the Weekend 1, which i though that it'll appear no more. That bug was so annoying, yet i began to find the reference to the Mario game, where Luigi is being opened as the playable character (which is it the Inside Story one or i just mistaken idhac honestly), which has a meme that say the opposite, so i inserted that meme as the response to that occurring bug out of my internal gamer rage. Also, i have noticed that there's some mistype on a title and then decided i fixed it so there'll be no confusion.

**Comment by Hundrec** [comment] 2024-10-31 16:27
Thanks for clarifying! In that case, this issue was already reported in https://github.com/FunkinCrew/Funkin/issues/3263.
You should close this issue and move your discussion to that one.

**Closed** 2024-11-01 11:20 UTC
Labels: status: duplicate
