### ISSUE TITLE
Bug Report: Noticeable part seams

### ISSUE THREAD

**Issue by omegaRubyy** [FunkinCrew/Funkin#3390] opened 2024-09-19 22:47 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Seams in Pico's parts for his Week 3 remix cutscenes are fairly noticeable. Note black lining across what appears to be the crotch and bridge in between eyes on both Picos in the cutscene. Screenshot from Windows build attached here
![screenshot-2024-09-19-18-35-14](https://github.com/user-attachments/assets/c145f02c-1407-4349-9a55-7242df692d6f)
I also found the issue present on Newgrounds, and I even noticed seams on the player select screen when the lock icon went into its unlocking animation. 
![Screenshot 2024-09-19 184217](https://github.com/user-attachments/assets/39c13b57-ec2b-4db6-bbc9-5e58a7a55f42)

### Steps to reproduce (or crash logs, errors, etc.)

Launch the game and play any Pico Mix song from Week 3. In the Newgrounds version, go to the Character Select screen and pay attention to the lock that gets replaced with Pico's icon.

**Comment by Hundrec** [comment] 2024-09-19 23:11
Partially reported in https://github.com/FunkinCrew/Funkin/issues/3216
This report adds the lock into the list

**Comment by EliteMasterEric** [comment] 2024-09-21 09:33
Duplicate of #3116.

**Closed by EliteMasterEric** 2024-09-21 09:33 UTC
Labels: status: duplicate
