### ISSUE TITLE
Bug Report: Mix songs show score from other characters

### ISSUE THREAD

**Issue by NotHyper-474** [FunkinCrew/Funkin#3145] opened 2024-09-13 03:41 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![Captura de tela 2024-09-13 003709](https://github.com/user-attachments/assets/89c27951-b87a-49af-b9df-ef2ae1ef4bf8)

![Captura de tela 2024-09-13 003850](https://github.com/user-attachments/assets/6a8ebe1f-a779-4b1d-8379-e8ec686d506f)
Also happens if you switch difficulty.

### Steps to reproduce (or crash logs, errors, etc.)

Go to Freeplay and hover over an BF song you've beaten, then switch to Pico.

**Comment by JordanSantiagoYT** [comment] 2024-09-13 03:47
this also happens for the pico songs btw, darnell bf mix shows the score for the pico version

**Comment by NotHyper-474** [comment] 2024-09-13 03:48
Now that I think about it this might be intentional to make it less inconvenient to check your score between characters. Will leave this open just in case.

**Comment by Squiddu** [comment] 2024-09-13 16:27
> this might be intentional to make it less inconvenient to check your score between characters

No, this is definitely a bug. Since the songs are drastically different both in sound and charts, there would be no reason to show the other score, plus having to assume the player knows what score they have for the other version and realizing that's what it was. The mixes just seem to have metadata branch off from the original songs, for whatever reason.

Clearly they can have seperate metadata related to the grades and song/artist titles, so I have no idea why score specifically is like this..

**Comment by JordanSantiagoYT** [comment] 2024-09-13 18:55
Even though the songs ARE drastically different, the files refer to both versions as the same song, the difference is the Pico Mix is a variation of the song, just like how Erect songs are a variation of the base song.

**Comment by JordanSantiagoYT** [comment] 2024-09-13 18:56
![image](https://github.com/user-attachments/assets/7deeb750-4d62-4fcb-9d83-1aa70d14c03f)
In fact, looking in the files proves this as true

**Comment by DaZapow** [comment] 2024-09-13 21:21
Do we know if this is purely a visual bug or if it actually saves to the wrong file? I forgot to back up my save data before updating and so if it actually saves to the wrong file I just lost my scores for Week 1 and Spookeez forever, considering there's no way I could override those scores with the BF version anymore considering I got 99-100% on all of the Pico mixes already

**Comment by EliteMasterEric** [comment] 2024-09-15 00:57
Confirmed and reproduced. Pico mixes for songs, similarly to Erect mixes for songs, are considered separate difficulties and store and display those scores separately.

Of note, scores appear to be SAVED correctly, so the next patch should make these visible with no data lost.

**Comment by EliteMasterEric** [comment] 2024-09-15 01:40
Fixed internally.

**Closed** 2024-09-18 19:14 UTC
Labels: type: minor bug, status: pending pull request
