### ISSUE TITLE
Bug Report: Pico broken animation + Unable to proceed on week 2

### ISSUE THREAD

**Issue by mrgayshit** [FunkinCrew/Funkin#3436] opened 2024-09-22 22:39 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

One: my pico animation at the third stage of weekend 1 is broken, I tried fixing it by restarting, but it didn't
![image](https://github.com/user-attachments/assets/c9f28c60-2b2e-4190-8eab-417b3ee77ff8)

I just can't proceed in week 2 (not because iI'm bad, but it just soft blocks m e (i can restart, but I won't proceed, so I'll just be stuck playing spookeez forever)

**Comment by JVNpixels** [comment] 2024-09-22 22:41
Please fill out the title! The Blazin' bug has been reported here at #3168, but the Week 2 bug is a new issue that will need to be fixed.

**Comment by mrgayshit** [comment] 2024-09-22 22:43
> Please fill out the title! The Blazin' bug has been reported here at #3168, but the Week 2 bug is a new issue that will need to be fixed.

Just did it! Sorry, it's my first time using this site

**Comment by JVNpixels** [comment] 2024-09-22 22:57
It is okay! No need to apologize, everyone has their first time with things!

**Comment by biomseed** [comment] 2024-09-22 23:16
> Please fill out the title! The Blazin' bug has been reported here at #3168, but the Week 2 bug is a new issue that will need to be fixed.

The week 2 bug is the song restarting and softlocking issue

**Comment by EliteMasterEric** [comment] 2024-09-23 02:40
Duplicate of #3142 and #3168

**Closed** 2024-09-23 02:41 UTC
Labels: status: duplicate
