### ISSUE TITLE
Compiling help: I get this error

### ISSUE THREAD

**Issue by AlexPlayzOG** [FunkinCrew/Funkin#2476] opened 2024-05-12 10:18 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'
[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
![error](https://github.com/FunkinCrew/Funkin/assets/126986198/a50c0842-65cc-4eb9-97f0-d6ba878557f4)
When I try to compile the source code, I get this error. I searched on internet about this error but I didn't find the solution.
### If anyone know how to solve it, help me.

**Comment by NotHyper-474** [comment] 2024-05-12 12:59
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2373

**Comment by AlexPlayzOG** [comment] 2024-05-12 15:52
> Duplicate of #2373

I fixed that error but now i get another one.

**Comment by AlexPlayzOG** [comment] 2024-05-12 15:53
> Duplicate of #2373

I fixed that error but now I get another one.

**Comment by AlexPlayzOG** [comment] 2024-05-12 15:53
ERROR  source/funkin/graphics/shaders/RuntimeCustomBlendShader.hx:14: characters 10-23

   14 |     this.setBitmapData("sourceSwag", value);
      |          ^^^^^^^^^^^^^
      | funkin.graphics.shaders.RuntimeCustomBlendShader has no field setBitmapData

**Comment by AlexPlayzOG** [comment] 2024-05-12 15:54
I dunno what to do now

**Closed** 2024-05-13 17:26 UTC
Labels: status: duplicate
