### ISSUE TITLE
Compiling help: (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

### ISSUE THREAD

**Issue by CasualCypress** [FunkinCrew/Funkin#2439] opened 2024-05-10 22:37 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

I keep having trouble with compiling this, I keep removing and installing stuff back and forth and i just need help PLS!!

source/Prebuild.hx:15: Building...
 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/polymod/git/polymod/Polymod.hx:1005: characters 1-7

 1005 | @:enum abstract PolymodErrorOrigin(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/polymod/git/polymod/Polymod.hx:1051: characters 1-7

 1051 | @:enum abstract PolymodErrorCode(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/polymod/git/polymod/backends/PolymodAssets.hx:226: characters 1-7

  226 | @:enum abstract PolymodAssetType(String) from String to String
      | ^^^^^^
      | (WDeprecatedEnumAbstract) `@:enum abstract` is deprecated in favor of `enum abstract`

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 WARNING  C:/Users/---/Desktop/Friday_Night_Funkin'/Engines/Vanilla/0.3.3/funkin/.haxelib/flixel/git/flixel/FlxState.hx:196: lines 196-199

  196 |  public function switchTo(nextState:FlxState):Bool
  197 |  {
  198 |   return true;
  199 |  }
      |
      | switchTo is deprecated, use startOutro

 ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

**Comment by amyspark-ng** [comment] 2024-05-10 22:45
https://github.com/FunkinCrew/Funkin/issues/2299

**Comment by EliteMasterEric** [comment] 2024-05-21 23:10
Duplicate of #2299.

**Closed by EliteMasterEric** 2024-05-21 23:10 UTC
Labels: status: duplicate
