### ISSUE TITLE
Bug Report: [my game crash]

### ISSUE THREAD

**Issue by Niox124** [FunkinCrew/Funkin#2896] opened 2024-06-23 20:39 UTC
i have no idear how to reproduce it but here is the file 
the game wase supose to keep going but it dont 
-->

## Desktop
 - OS:
 
 - Version:
 

## Additional context

https://github.com/FunkinCrew/Funkin/assets/173632089/20910ee8-5baa-4114-8b2c-9cf7d04740a2

**Comment by Niox124** [comment] 2024-06-23 20:40
sorry idk much

**Comment by Niox124** [comment] 2024-06-23 20:41
the file is https://drive.google.com/file/d/1Kvqo5I750qBwym8H9ONGDOF1v1qQls3g/view?usp=drive_link

**Comment by Hundrec** [comment] 2024-06-23 21:01
Is this a modified build? 
If so, how?

(The Google Drive file is inaccessible)

**Comment by Niox124** [comment] 2024-06-24 14:39
no it not and wait i am going to make it accessible

**Comment by Niox124** [comment] 2024-06-24 14:42
https://drive.google.com/file/d/1Kvqo5I750qBwym8H9ONGDOF1v1qQls3g/view?usp=drive_link

**Comment by Niox124** [comment] 2024-06-24 14:45
@Hundrec welp now i think it up and if it still not working we coud just share it by  e-mails

**Comment by ninjamuffin99** [comment] 2024-06-24 17:37
this might be a duplicate of the other mac opening bug!

**Closed** 2024-06-24 17:37 UTC
Labels: status: duplicate

**Comment by Niox124** [comment] 2024-06-24 17:42
alr
