### ISSUE TITLE
Bug Report: Pico and Darnell's Blazin sprites incorrectly positioned

### ISSUE THREAD

**Issue by MrTie-fixer** [FunkinCrew/Funkin#3419] opened 2024-09-21 15:46 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/354b904f-d34d-49e9-ab90-ae8496c454f4)

https://github.com/user-attachments/assets/527b0ad5-331f-480f-99e8-fbdf7f698dc7

### Steps to reproduce (or crash logs, errors, etc.)

To reproduce this bug, pause the game when you play Blazin' and then restart the song.

**Comment by JVNpixels** [comment] 2024-09-21 16:06
Already reported at #3168, but thank you for submitting anyway! You can now close this.

**Comment by EliteMasterEric** [comment] 2024-09-22 04:05
Duplicate of #3168

**Closed by EliteMasterEric** 2024-09-22 04:05 UTC
Labels: status: duplicate
