### ISSUE TITLE
Bug Report: A bug for songs with long names

### ISSUE THREAD

**Issue by Fereskable** [FunkinCrew/Funkin#2703] opened 2024-06-08 13:21 UTC
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.4.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Change the difficulty while your on Winter Horrorland (or any song with along name, but this does not affect erect remixes)

## Please describe your issue. Provide extensive detail and images if possible.

Songs with long names look like this when you change the difficulty.

![screenshot-2024-06-08-16-17-25](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/00f012f1-3fc7-43f5-9b1f-11927c66816b/0daaae0e-ef3f-41d9-9d0d-f7a77ce2ca7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi8wMGYwMTJmMS0zZmM3LTQzZjUtOWIxZi0xMTkyN2M2NjgxNmIvMGRhYWFlMGUtZWYzZi00MWQ5LTlkMGQtZjdhNzdjZTJjYTdkIiwiaWF0IjoxNzE4MDU1NTc1LCJleHAiOjMzMjg4NjE1NTc1fQ.LUjtJxKuqnTGwPndbWLEf_jGNy0SahDoUhLw-VHXhVc)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by Hundrec** [comment] 2024-06-08 16:22
Seems like the same bug as https://github.com/FunkinCrew/Funkin/issues/2659 and https://github.com/FunkinCrew/Funkin/issues/2682

They're working on a fix soon!

**Comment by ninjamuffin99** [comment] 2024-06-12 20:40
may or may not be fixed in 0.4.1, if this bug is still being run into let me know!

**Comment by EliteMasterEric** [comment] 2024-06-17 02:52
Duplicate of #2659.

**Closed by EliteMasterEric** 2024-06-17 02:52 UTC
Labels: status: duplicate
