### ISSUE TITLE
Bug Report: Misaligned Retry on Pico Christmas Game Over

### ISSUE THREAD

**Issue by CharGoldenYT** [FunkinCrew/Funkin#3361] opened 2024-09-18 07:19 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

![image](https://github.com/user-attachments/assets/fd86fe1b-ec77-4864-8eed-26ec6b57086e)

### Steps to reproduce (or crash logs, errors, etc.)

**_Die._** (in Eggnog pico mix)

**Comment by EliteMasterEric** [comment] 2024-09-18 07:23
Duplicate of #3179

**Closed by EliteMasterEric** 2024-09-18 07:23 UTC
Labels: status: duplicate

**Comment by CharGoldenYT** [comment] 2024-09-18 07:28
oop, I didnt search the right terms it seems.
