### ISSUE TITLE
Bug Report: the list in the animation editor can't be seen 

### ISSUE THREAD

**Issue by gdplayer9000000** [FunkinCrew/Funkin#3569] opened 2024-10-04 14:39 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

v0.5.0

### Description (include any images, videos, errors, or crash logs)

in the animation editor the lists to change animation or character sprites can't be seen making it impossible to change the character sprites from bf

### Steps to Reproduce

1. open the downloadable version of Friday night funkin 
2. go to options and go to controls and choose a control for menu 
3. go to main menu and press the button you chose for menu 
4. press enter on the selection that says Animation Editor 
5. then you'll see that's there's no way to edit the animations

**Comment by AbnormalPoof** [comment] 2024-10-04 14:51
Duplicate of #3151

**Closed** 2024-10-05 01:28 UTC
Labels: status: duplicate

**Comment by NotHyper-474** [comment] 2024-10-05 01:29
Woah
