### ISSUE TITLE
Bug Report:  pixelated icons do not display correctly in the chart editor

### ISSUE THREAD

**Issue by ImNot4ntony** [FunkinCrew/Funkin#3299] opened 2024-09-15 10:15 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0 (Playable pico Update)

### Context (Provide images, videos, etc.)

I entered the chart editor to play Darnell Bf Mix and then when I checked if there were no more changes I realized that they broke the icons by adding animations to them in freeplay LOL, A simple solution to this is to make a separate sprite without animation, or program its animation in the chart editor
![image](https://github.com/user-attachments/assets/37364267-b67e-41e8-8f65-1de8ec37fce8)

### Steps to reproduce (or crash logs, errors, etc.)

enter the chart editor on any song and change the character

**Comment by EliteMasterEric** [comment] 2024-09-18 09:09
Duplicate of #3148

**Closed by EliteMasterEric** 2024-09-18 09:09 UTC
Labels: type: minor bug, status: duplicate
