### ISSUE TITLE
Compiling help: Uncaught exception Eof

### ISSUE THREAD

**Issue by fianalins** [FunkinCrew/Funkin#2592] opened 2024-05-22 22:39 UTC
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
```
ERROR  C:\HaxeToolkit\haxe\std/haxe/io/Input.hx:189: characters 37-42

 189 |     #if neko neko.Lib.rethrow #else throw #end (e);
     |                                     ^^^^^
     | Uncaught exception Eof

      ->  source/funkin/util/macro/GitCommit.hx:23: characters 29-54

       23 |     var commitHash:String = process.stdout.readLine();
          |                             ^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here

      ->  source/funkin/util/Constants.hx:101: characters 41-87

      101 |   public static final GIT_HASH:String = funkin.util.macro.GitCommit.getGitCommitHash();
          |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          | Called from here
```

![image](https://github.com/FunkinCrew/Funkin/assets/87100196/8443791e-50bc-4f0c-a548-c5656c3a66c0)

I haven't changed anything in the source code, I downloaded the proper repositories and I went through the hmm command. What could I have possibly done wrong? I don't understand.

I had gotten an error for `JsonParser_0 has no field ignoreUnknownVariables` so I installed the hmm command and did `hmm install` in my repo folder and it got rid of the error, but in turn made this one appear.

I am not very fluent in this stuff, especially with Haxe code so I have no clue what this means.

**Comment by NotHyper-474** [comment] 2024-05-22 22:57
Duplicate of #2392

**Closed** 2024-06-14 19:30 UTC
Labels: status: duplicate
