### ISSUE TITLE
Bug Report: ERECT Mode Week 2 Boyfriend doesn't properly have his game over screen

### ISSUE THREAD

**Issue by Banjoei** [FunkinCrew/Funkin#3317] opened 2024-09-16 03:01 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When you die in Week 2 ERECT, the bone break noise plays, but the death screen just has Boyfriend (Dark)'s sprite frozen from the last frame of animation before you die. The game over music also isn't set to play.

![image](https://github.com/user-attachments/assets/9f0c29bb-7a31-4961-be31-d0c158655147)
![image](https://github.com/user-attachments/assets/150c7b7a-440e-4dcd-ad3c-e463279c4b2b)

### Steps to reproduce (or crash logs, errors, etc.)

During an ERECT mode Week 2 song, press R or miss enough notes to trigger a Game Over screen

**Comment by MrMooey** [comment] 2024-09-16 03:05
Duplicate of #3233

**Comment by JVNpixels** [comment] 2024-09-16 03:05
Reported already
Duplicate of #3233.
Please close!

**Closed** 2024-09-16 08:10 UTC
Labels: status: duplicate
