### ISSUE TITLE
Bug Report: End of the song ''Ugh'' - Nightmare difficult 

### ISSUE THREAD

**Issue by Matix1212** [FunkinCrew/Funkin#3847] opened 2024-11-10 15:02 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Opera

### Version

v0.5.3

### Description (include any images, videos, errors, or crash logs)

Whenever I finish the ''Ugh'' song in ''Nightmare'' difficult, the audio remains on repeat and I can't stablish a record for the song, since it never ends. 

### Steps to Reproduce

1- Play ''Ugh'' song, nightmare difficult with Boyfriend.
2- Finish the song.
3- The song remains on replay.
4- You can't stablish a record or completely finish the song.

**Comment by NotHyper-474** [comment] 2024-11-10 15:11
Duplicate of #3142

**Comment by Matix1212** [comment] 2024-11-12 00:23
-

**Closed** 2024-11-12 00:23 UTC
Labels: status: duplicate

**Comment by Beelijah** [comment] 2024-11-12 22:25
-
