### ISSUE TITLE
Bug Report: game crashes if you lose in minimal playtest

### ISSUE THREAD

**Issue by imadeagithubaccountforthis** [FunkinCrew/Funkin#2420] opened 2024-05-09 23:03 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Step 1:open up chart editor
Step 2:playtest (minimal mode)
Step 3:lose (by spamming notes)
## Please describe your issue. Provide extensive detail and images if possible.
![image](https://github.com/FunkinCrew/Funkin/assets/81992759/ac5eb1d0-ee34-4622-97eb-f86f56109857)

**Comment by JackXson-Real** [comment] 2024-05-10 05:04
Duplicate of #2280

**Comment by EyeDaleHim** [comment] 2024-05-10 17:07
> Duplicate of #2280

We should redirect that issue to here instead, this does a much better job of presenting the actual issue.

**Comment by imadeagithubaccountforthis** [comment] 2024-05-10 21:01
honestly im just 99% sure its because of the boyfriend object being missing during minimal playtesting

**Comment by EliteMasterEric** [comment] 2024-05-22 21:16
Should be fixed by #2518.

**Comment by EliteMasterEric** [comment] 2024-06-17 02:35
should be resolved

**Closed by EliteMasterEric** 2024-06-17 02:35 UTC
Labels: type: major bug, status: resolved
