### ISSUE TITLE
pixelated note sparks missing from week 6

### ISSUE THREAD

**Issue by JabbingQuirker** [FunkinCrew/Funkin#2338] opened 2024-05-08 14:38 UTC
As title says, when hitting sick notes in week 6, the pixelated little note sparks are missing :(

(itch version)

**Comment by moxie-coder** [comment] 2024-05-08 14:43
pretty sure that was intentional, not a bug unless they’re working on pixel splashes which is why there’s none rn

**Comment by JackXson-Real** [comment] 2024-05-08 17:21
I believe its because they are working on new ones that also support the new hold arrow splashes.

**Comment by EliteMasterEric** [comment] 2024-06-17 02:50
Duplicate of #2823, that one has more info.

**Closed by EliteMasterEric** 2024-06-17 02:50 UTC
Labels: status: duplicate

**Comment by Michu0204** [comment] 2025-03-31 21:03
Added in 0.6.0

**Comment by AbnormalPoof** [comment] 2025-03-31 21:13
> Added in 0.6.0

This is a duplicate.
