### ISSUE TITLE
Bug Report: Splash effect don't work in week 6

### ISSUE THREAD

**Issue by MrBossGuy36** [FunkinCrew/Funkin#3009] opened 2024-07-12 00:32 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

Basically, the splash effects on week 6 don't work. I remember playing week 6 before the weekend 1 update and it was working perfectly.

**Comment by Hundrec** [comment] 2024-07-12 01:02
Dev response in #2823

**Comment by EliteMasterEric** [comment] 2024-07-12 01:38
Duplicate of #2823

**Closed by EliteMasterEric** 2024-07-12 01:38 UTC
Labels: type: minor bug, status: duplicate

**Comment by MrBossGuy36** [comment] 2024-07-14 01:22
@EliteMasterEric Oh im sorry, mustve missed it. My bad.
