### ISSUE TITLE
Bug Report: Song capsule interface offset in freeplay

### ISSUE THREAD

**Issue by funkysvyat** [FunkinCrew/Funkin#3418] opened 2024-09-21 14:55 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.50

### Context (Provide images, videos, etc.)

I played Darnell BF Mix on normal difficulty and after finishing the song the UI in free play shifted. idk why.
![interface offset](https://github.com/user-attachments/assets/7d8dab3d-48d5-4c31-a6aa-0ec8f19c92ac)

also theres a video, demostrating this.
https://github.com/user-attachments/assets/230cf38d-8315-40c5-9cbb-cd93975acd35

### Steps to reproduce (or crash logs, errors, etc.)

play darnell bf mix (norm) -> go to freeplay

**Comment by AbnormalPoof** [comment] 2024-09-21 17:45
Duplicate of #3239.

**Comment by EliteMasterEric** [comment] 2024-09-22 04:05
Duplicate

**Closed by EliteMasterEric** 2024-09-22 04:05 UTC
Labels: status: duplicate
