### ISSUE TITLE
Bug Report: Free Play Crashes on Linux V 0.2.7.1

### ISSUE THREAD

**Issue by HurricanePootis** [FunkinCrew/Funkin#554] opened 2021-03-08 03:30 UTC
### If you are playing a downloaded version of the game, what operating system are you using?
Arch Linux x86_64

## What version of the game are you using? Look in the bottom left corner of the main menu.
V. 0.2.7.1 compiled from the source .tar.gz under the Github releases

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1) Launch Game
2) Click Free Play
3) Crash
## Please describe your issue. Provide extensive detail and images if possible.
My issue is that I am unable to use freeplay mode on the Linux build of Funkin Friday Night. Here is what the terminal outputs whenever I am using the debug binary:
```
borowski@TheCloutPC ~/Funkin/export/debug/linux/bin $ ./Funkin 
source/NGio.hx:38: INIT NOLOGIN
source/TitleState.hx:279: OLD VERSION!
source/MusicBeatState.hx:25: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
xdg-open: unexpected argument '&'
Try 'xdg-open --help' for more information.
source/MusicBeatState.hx:25: reg (x: -200 | y: -200 | w: 1792 | h: 1008)
source/MainMenuState.hx:174: Freeplay Menu Selected
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1949
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1165
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 516
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 178
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 545
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 724
Called from flixel.FlxGame::switchState flixel/FlxGame.hx line 637
Called from FreeplayState::create FreeplayState.hx line 120
Called from FreeplayState::changeSelection FreeplayState.hx line 234
Error : Null Object Reference
borowski@TheCloutPC ~/Funkin/export/debug/linux/bin :( $
```

**Comment by DjBRINE** [comment] 2021-03-08 05:55
This report is a dupe of #410. 
Here's the temporary solution: https://github.com/ninjamuffin99/Funkin/issues/501#issuecomment-787261843

**Closed** 2024-05-08 07:03 UTC
Labels: legacy
