### ISSUE TITLE
Bug Report: selecting  Pico on freeplay doesn't save

### ISSUE THREAD

**Issue by Szymonkruk12** [FunkinCrew/Funkin#3837] opened 2024-11-06 14:09 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5..3

### Description (include any images, videos, errors, or crash logs)

Please fix that

### Steps to Reproduce

1. select pico in character select
2. quit game
3. check freeplay

**Comment by GoombarioFan** [comment] 2024-11-07 06:11
Seems to be more or less a duplicate of #3689, which is a feature request instead of a bug report.

**Closed** 2024-11-18 23:18 UTC
Labels: type: minor bug, status: duplicate
