### ISSUE TITLE
Bug Report: incorrect freeplay screen

### ISSUE THREAD

**Issue by MrCatPlays** [FunkinCrew/Funkin#3235] opened 2024-09-13 23:43 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I played and beat every new stage yesterday, including redoing Weekend1 and playing the new BF mix. But when I opened the game today, it gave me the "New Character Unlocked" screen, asking me to press Tab to switch characters.

![image](https://github.com/user-attachments/assets/c65eec71-549c-4f39-bed1-51982cfc1c5c)

After I opened the character select screen, it acted like I never opened it before and "rewarded me" with the option to play as Pico.

![image](https://github.com/user-attachments/assets/4e9168f7-0146-4be9-8215-ef97c6b0ba55)

Any idea why?

**Comment by AbnormalPoof** [comment] 2024-09-13 23:44
Duplicate of #3165

**Closed** 2024-09-14 00:00 UTC
Labels: status: duplicate
