### ISSUE TITLE
Bug Report: the tracklist is bugged in the storymode menu when compiling the game

### ISSUE THREAD

**Issue by Pinks8n** [FunkinCrew/Funkin#990] opened 2021-05-01 01:17 UTC
tutorial doesnt show up and neither does the 3rd song of any of the other weeks

**Comment by VMGuy23** [comment] 2021-05-01 19:55
Same problem here- think its a duplicate

**Comment by VMGuy23** [comment] 2021-05-01 19:57
Duplicate of #932

**Comment by Pinks8n** [comment] 2021-05-02 00:52
ty

**Comment by VMGuy23** [comment] 2021-05-02 07:12
Type `haxelib git openfl https://github.com/openfl/openfl` to fix the issue

**Closed** 2024-05-08 07:00 UTC
Labels: legacy
