### ISSUE TITLE
Bug Report:the chart editor is broken (again -_-)

### ISSUE THREAD

**Issue by asd3fg** [FunkinCrew/Funkin#3309] opened 2024-09-15 19:19 UTC
### Issue Checklist

- [x] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Windows

### Version

pico playable update

### Context (Provide images, videos, etc.)

![screenshot-2024-09-15-15-19-31](https://github.com/user-attachments/assets/26f35aa6-e834-4459-ba92-95c410832e59)
Vowels with the name "Voices" do not work

I can't choose characters from their top icon, the pixel icons are wrong, and I can't chart with mouse clicks

### Steps to reproduce (or crash logs, errors, etc.)
go to the chart editor

**Comment by charlesisfeline** [comment] 2024-09-15 22:23
dupe of #3147

**Comment by EliteMasterEric** [comment] 2024-09-16 20:25
Duplicate

**Closed by EliteMasterEric** 2024-09-16 20:25 UTC
Labels: status: duplicate
