### ISSUE TITLE
Bug Report: Darnell (Bf Mix) gone from freeplay menu

### ISSUE THREAD

**Issue by WhatIsThisPl** [FunkinCrew/Funkin#3504] opened 2024-10-01 01:56 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Google Chrome

### Version

v0.5.1

### Description (include any images, videos, errors, or crash logs)

In the freeplay menu for boyfriend the Darnell mix is missing
![Screenshot (2)](https://github.com/user-attachments/assets/b46a92b1-0cf4-41fe-8229-1aa798718521)

**Comment by NotHyper-474** [comment] 2024-10-01 02:10
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3487

**Comment by Johnsen290** [comment] 2024-10-01 10:19
it's not gone btw, songs are now separated into two categories, originals and char specific remixes, to cycle between categories, hover to random and cycle through the difficulties. once you return back to easy, the category will be changed, this wasn't cleared up at all, nor the changelogs tell this

**Comment by NotHyper-474** [comment] 2024-10-01 11:40
I don't think it was intentional either way

**Comment by EliteMasterEric** [comment] 2024-10-01 14:12
Duplicate

**Closed by EliteMasterEric** 2024-10-01 14:12 UTC
Labels: status: duplicate
