### ISSUE TITLE
Bug Report: Failure to boot on prebuilt linux build on Itch.io

### ISSUE THREAD

**Issue by Dal1ster** [FunkinCrew/Funkin#2759] opened 2024-06-12 03:47 UTC
## Describe the bug
When trying to launch the prebuilt linux version of fnf found on the itch page (under funkin-linux-64bit.zip), when i try to launch it via ./Funkin it spits out an error in the terminal and doesent launch at all. Ive made sure the library mentioned in the error is installed and i presume it already was as well (OS is POP_OS!, latest version of their site)

## To Reproduce
Download the funkin-linux-64bit.zip file onto linux distro of choice
Extract files to directory and make sure funkin is marked as an executable
open terminal and type in ./Funkin
error pops out and game doesent open
## Expected behavior
I expected the executable to accept the command and launch the game from it, allowing me access to the game and gameplay.

## Screenshots/Video

![Screenshot from 2024-06-11 22-45-36](https://github.com/FunkinCrew/Funkin/assets/76823236/2d44cdca-4dfe-4098-bf93-ea4fae8e594d)
this shows what was already listed in the console, just as a screenshot in case

## Desktop
 - OS:
 (from hyfetch) Pop!_OS bookworm/sid (jammy) x86_64
 - Browser
This is about the dedicated desktop builds, so none
 - Version:
Unknown, cannot boot the game to see, but i presume it is the WeekEnd update build released 4 days ago as of this issue being made

## Additional context
Extra info from hyfetch for context
Kernel: 6.8.0-76060800daily20240311-generic 
Packages: 2310 (dpkg), 11 (steam), 11 (flatpak-user) 
Shell: bash 5.1.16 
Resolution: 2560x1440 @ 99.95Hz, 1920x1200 @ 59.95Hz 
DE: GNOME 42.9 (x11) 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] Cursor: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-9600K (6) @ 4.6GHz 
GPU: NVIDIA GeForce RTX 3060 Lite Hash Rate 
Memory: 9.06 GiB / 31.26 GiB (28%) 
Network: 1 Gbps; Wifi (Both wired to router and connected to wifi)
Bluetooth: Intel Corp. AX210 
BIOS: American Megatrends Inc. 5.13 (01/06/2021)

**Comment by NotHyper-474** [comment] 2024-06-12 12:16
I already expected this to happen.

Unfortunately the FunkinCrew built their Lime libraries using a very recent version of GLibC, which prevents systems that use older versions to run the game. 

And there's no feasible way to upgrade GLibC since a lot of system stuff that rely on it might break.

I think you can just replace the lime.ndll file with one built with an older GLibC, I'll try sending mine here, just hold up

**Comment by NotHyper-474** [comment] 2024-06-12 17:10
Alright, could you try [my build](https://github.com/NotHyper-474/Funkin/releases/tag/v0.4.0) of the game? It was built using Ubuntu 20.04 so it should only require GLibC 2.31 at minimum

**Comment by Dal1ster** [comment] 2024-06-12 17:19
Currently away from pc due to a day trip, but I will test the build as soon
as possible

**Comment by Dal1ster** [comment] 2024-06-12 23:51
Alright, finally home, and i tested your build and found out 2 things:
Firstly your build of the game works, i saw the title screen boot and the game version is 0.4.0, and
Secondly, the version of GLIBC i have with the system according to ldd --version is 2.35

**Comment by NotHyper-474** [comment] 2024-06-13 00:09
> Alright, finally home, and i tested your build and found out 2 things: Firstly your build of the game works, i saw the title screen boot and the game version is 0.4.0, and Secondly, the version of GLIBC i have with the system according to ldd --version is 2.35
> 
> Cutscenes also seem to work as well, although i did make sure to install vlclib before launching testing with WeekEnd 1, song seems to be in sync with notes and the game doesent seem to be spitting out any errors or slowdown

Perfect, so it's working as intended. I'll soon be pushing out the 0.4.1 version (specially since they didn't build it yet...)

**Comment by EliteMasterEric** [comment] 2024-06-16 04:10
Duplicate of #2778.

**Closed by EliteMasterEric** 2024-06-16 04:10 UTC
Labels: status: duplicate
