### ISSUE TITLE
Game hangs and crashes on white screen when pressing enter twice right after the HaxeFlixel startup screen

### ISSUE THREAD

**Issue by actuallyasmartname** [FunkinCrew/Funkin#577] opened 2021-03-13 01:17 UTC
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
Tried everything, especially reinstalling 
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Not playing on browser.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Not playing on browser.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows x64

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
1. Launch FNF
2. On the HaxeFlixel startup screen, spam enter. Keep on spamming even after the HaxeFlixel screen is over.
## Please describe your issue. Provide extensive detail and images if possible.
The game hangs on a white screen with the cursor being seen, and then a few seconds later crashes the game

**Comment by MarioLuigi124** [comment] 2021-03-13 09:35
you will have not spam enter...

**Comment by matthew99729** [comment] 2021-03-13 18:39
I'm face palming so hard right now. This happens with the pc game too. Just don't touch your screen when the game is using a lot of power to load stuff quickly lol.

**Comment by matthew99729** [comment] 2021-03-13 18:40
I'm face palming so hard right now. Just don't touch anything when the game is using a lot of power to load stuff quickly lol.

**Comment by Epictyphlosion** [comment] 2021-03-13 19:38
> 
> 
> I'm face palming so hard right now. Just don't touch anything when the game is using a lot of power to load stuff quickly lol.

Even so, it'd be better to have it fixed instead of telling the player to avoid it.

**Comment by EpilepticSoldier** [comment] 2021-03-14 04:10
I did some testing and I know what the problem is.
Just when the cursor appears, when you press enter two times fast the game crashes. If you press it only once, however, the credits play as usual but never transition to the main screen with Girlfriend.
So, the problem should be that the main screen skip code is called before the credits appear. And when you press enter two times, the game doesn't what to do and it crashes.

**Comment by Speedrunner-doomguy** [comment] 2021-03-15 20:57
I wrote about this a month or so ago experiencing the issue too when 2.7.1 was freshly made the day before and I figured out that the version previous actually has this bug fixed so its an odd thing, also Im really impatient so spamming enter is my go to for testing out mods that i need to troubleshoot

**Comment by actuallyasmartname** [comment] 2021-03-16 13:30
#428

**Comment by dinkstr** [comment] 2021-03-18 04:02
Possibly related to #562?

**Comment by actuallyasmartname** [comment] 2021-03-18 19:26
> Possibly related to #562?

Kinda, but instead of a black screen it's a white screen. Also this happens right after the HaxeFlixel startup splash

**Closed** 2024-05-08 07:03 UTC
Labels: legacy
