### ISSUE TITLE
Bug Report: Weird inconsistency with scores, and ranks and freeplay. (Playing on windows build)

### ISSUE THREAD

**Issue by classicsonic2d** [FunkinCrew/Funkin#2736] opened 2024-06-10 03:35 UTC
I played Satin Panties Nightmare and got a FC, no misses, all Good and Sicks.
The 100% rank animation plays normally, same with the P Rank animation in the Freeplay menu. But, for some reason, the percent of completion of the song is 99%, while the P Rank icon is on Satin Panties button.
![Screenshot 2024-06-09 232444](https://github.com/FunkinCrew/Funkin/assets/126111132/645faa6e-92b1-4319-b4ba-f270d8b315e7)

I leave the Freeplay menu, then come right back.
Then the P Rank just magically turns into a E Rank.
![Screenshot 2024-06-09 232542](https://github.com/FunkinCrew/Funkin/assets/126111132/d4e7647d-f3d6-4d1d-b8b7-ed31de367da9)

This actually happened two times today, actually.

**Comment by Hundrec** [comment] 2024-06-10 03:42
This issue was reported here: https://github.com/FunkinCrew/Funkin/issues/2664

**Comment by EliteMasterEric** [comment] 2024-06-11 05:02
Valid issue but duplicate of #2664, which I have set to a current pin.

**Closed by EliteMasterEric** 2024-06-11 05:02 UTC
Labels: status: duplicate
