### ISSUE TITLE
Bug Report: Chart Editor in 0.5.0 doesn't allow placement of notes.

### ISSUE THREAD

**Issue by pixl006** [FunkinCrew/Funkin#3283] opened 2024-09-14 21:26 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

https://github.com/user-attachments/assets/9e6348ed-2c60-40de-ad72-15b085ea6262

As per the video, attempting to click anything on the lanes in the chart editor doesn't place notes. I did try with 0.4.1 and it works without problems, yet trying on 0.5.0, nothing happens. I can clearly remove notes but I just cannot place anything other than by using the live input mode.

### Steps to reproduce (or crash logs, errors, etc.)

1. Open the game,
2. _Enjoy the music_,
3. Open the chart editor using preferred bind,
4. Attempt to click **anything** on the lanes for notes or events,
5. Realise it isn't working,
6. _Sad :(_

**Comment by NotHyper-474** [comment] 2024-09-14 21:27
Duplicate of #3147

**Comment by EliteMasterEric** [comment] 2024-09-16 20:25
Duplicate

**Closed by EliteMasterEric** 2024-09-16 20:25 UTC
Labels: status: duplicate
