### ISSUE TITLE
Bug Report: Choosing pico instrumental on erect songs causes song to end early

### ISSUE THREAD

**Issue by InsanityGrasp** [FunkinCrew/Funkin#3341] opened 2024-09-17 03:46 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When selecting erect songs, the game will sometimes give you the option to chose the pico instrumental. If you do this on pico erect / night, the song will glitch out and end early.

### Steps to reproduce (or crash logs, errors, etc.)

Open game, do not switch to pico (keep the glowy animation) select pico night, choose pico instrumental & play.

**Comment by MrMooey** [comment] 2024-09-17 06:00
Duplicate of #3269

**Comment by EliteMasterEric** [comment] 2024-09-17 08:13
Duplicate

**Closed by EliteMasterEric** 2024-09-17 08:13 UTC
Labels: status: duplicate
