### ISSUE TITLE
Selecting the WHOLE opponent section actually selecting left arrows in your section

### ISSUE THREAD

**Issue by lancer9991** [FunkinCrew/Funkin#3072] opened 2024-07-28 15:58 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.4.1

### Context (Provide images, videos, etc.)

"The video is too big"
https://youtu.be/L9-i7T2AqoU

### Steps to reproduce (or crash logs, errors, etc.)

idk what this means

**Comment by tposejank** [comment] 2024-07-28 16:08
![Screenshot_20240728_120546_Brave](https://github.com/user-attachments/assets/62d8f9c7-3fd8-49ea-874c-feef790aeb27)

If you want to select all opponents' notes, click on "Mommy Mearest (Car)." Otherwise, by doing the method you showcased, you should say goodbye to your FPS and your memory.

You may mark this issue as complete.

**Comment by NotHyper-474** [comment] 2024-07-28 16:15
Seems like it's related to #2657

**Comment by Average-FNF-Modder** [comment] 2024-07-30 23:27
> ![Screenshot_20240728_120546_Brave](https://private-user-images.githubusercontent.com/81495861/352851764-62d8f9c7-3fd8-49ea-874c-feef790aeb27.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzODIyMzcsIm5iZiI6MTcyMjM4MTkzNywicGF0aCI6Ii84MTQ5NTg2MS8zNTI4NTE3NjQtNjJkOGY5YzctM2ZkOC00OWVhLTg3NGMtZmVlZjc5MGFlYjI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDIzMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZjI2M2FhMmU5MWQ3NzM0NDk2OGNhNTdiMjgwMDI1M2U5ZDhkNWI2NmUwNmQ1ODNkNWIyNTBhYzJmYzNlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHc5uMhXqcIElEApi90O3t3AdPD4tPF5WOf5ACsYKcQ)
> 
> If you want to select all opponents' notes, click on "Mommy Mearest (Car)." Otherwise, by doing the method you showcased, you should say goodbye to your FPS and your memory.
> 
> You may mark this issue as complete.

Still an issue as this happens even when not selecting the full chart. Notes you didn't select, shouldn't be selected! Definitely still a bug worth fixing.

**Comment by EliteMasterEric** [comment] 2024-09-22 05:15
Duplicate of #2657 .

**Closed by EliteMasterEric** 2024-09-22 05:15 UTC
Labels: status: duplicate
