### ISSUE TITLE
[COMPILING] Polymod causing compile issues (extra field coreAssetRedirect)

### ISSUE THREAD

**Issue by Eviethecoder** [FunkinCrew/Funkin#2299] opened 2024-05-08 01:56 UTC
When compiling the new base game code. the pollymod handeler seems to be givving out errors

 ERROR  source/funkin/modding/PolymodHandler.hx:294: characters 7-24

  294 |       coreAssetRedirect: CORE_FOLDER,
      |       ^^^^^^^^^^^^^^^^^
      | { coreAssetRedirect : Null<String>, assetLibraryPaths : haxe.ds.Map<String, String> } has extra field coreAssetRedirect

i have followed the compileguide. and even reinstalled everything from scratch. same isues

**Comment by EliteMasterEric** [comment] 2024-05-08 02:21
It definitely sounds like you didn't complete the steps in the guide correctly. That message appears if you are using an old version of Polymod.

Make sure to properly use `hmm`.

**Comment by EliteMasterEric** [comment] 2024-05-08 02:47
Okay I'm going to try to reproduce this error on my machine

**Comment by Eviethecoder** [comment] 2024-05-08 03:24
alrighty! i also tried manually downloading the github release and replacing it with no luck

**Comment by EliteMasterEric** [comment] 2024-05-08 06:49
This is definitely caused by an outdated Polymod version, but this can happen if `hmm` fails to install libraries and stops midway through.

**Comment by Eviethecoder** [comment] 2024-05-08 11:35
Is their any fix if it continuously happens

**Comment by Eviethecoder** [comment] 2024-05-08 18:03
Did you check your .haxelib folder l?

**Comment by METGameDev** [comment] 2024-05-08 19:33
Ok, i found a fix (i think)
1. delete the .haxelib folder in your repo
2. remove funkin.vis from hmm so it doesnt crash halfway through
3. run and install hmm
4. install funkin.vis

i THINK that should be it. tell me if this works

**Comment by METGameDev** [comment] 2024-05-08 23:28
dw bout it

**Comment by MulakkJ** [comment] 2024-05-09 12:54
> dunno if this helps, but polymod isnt being added into the lib folder. searched around and cant seem to find any instance of it even after installing it. ![image](https://private-user-images.githubusercontent.com/76184245/328990180-47acf960-6d29-4450-a8de-77037263e566.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTk0NDksIm5iZiI6MTcxNTI1OTE0OSwicGF0aCI6Ii83NjE4NDI0NS8zMjg5OTAxODAtNDdhY2Y5NjAtNmQyOS00NDUwLWE4ZGUtNzcwMzcyNjNlNTY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDEyNTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZWZkMzBmNWZjZjg1NzBmMWM4YjJmNGMxNmMwYWIzN2QxNzNlMDQzNDI2NWE2ODI5NjljZjI2OWUyZmVhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1GdxLHH0SVGyIoL5vve6KWI7BTkpOX1lrv4jgnXVZ1I)

what folder is this?

**Comment by MulakkJ** [comment] 2024-05-09 15:02
> 1. delete the .haxelib folder in your repo

where is the repo? i cant locate it

**Comment by moxie-coder** [comment] 2024-05-09 19:30
> > 1. delete the .haxelib folder in your repo
> 
> where is the repo? i cant locate it

it should be on your computer

**Comment by MulakkJ** [comment] 2024-05-10 18:47
> > > 1. delete the .haxelib folder in your repo
> > 
> > 
> > where is the repo? i cant locate it
> 
> it should be on your computer if you cloned it already

nvm found it

**Comment by pahaze** [comment] 2024-05-16 19:43
> Ok, i found a fix (i think)
> 
>     1. delete the .haxelib folder in your repo
> 
>     2. remove funkin.vis from hmm so it doesnt crash halfway through
> 
>     3. run and install hmm
> 
>     4. install funkin.vis
> 
> 
> i THINK that should be it. tell me if this works

This did not work for me. I've tried this, installing polymod manually, all the other goodies to no avail. Looking at the source of polymod given by git, it's missing the wanted argument entirely.

![image](https://github.com/FunkinCrew/Funkin/assets/69173292/5df39113-4cbd-48d5-a8a3-a6be9f553e44)

Looking a little more... the issue isn't an outdated version of polymod, ironically it's that it's too new. hmm doesn't seem to follow the commit given in the JSON, because on the latest commit in `master`, `coreAssetRedirect` is not a variable in `FrameworkParams`.

![image](https://github.com/FunkinCrew/Funkin/assets/69173292/19b0fc02-aec8-44a2-ac57-0434a3aaa88b)

But, in the correct commit, it does contain the missing argument.

![image](https://github.com/FunkinCrew/Funkin/assets/69173292/ba485806-192f-4e55-b7a3-ad6ccdfcf4b9)

So... hmm at fault? :joy:

**Comment by pahaze** [comment] 2024-05-16 19:52
Changing the ref to `develop` in hmm, removing Polymod's folder (.haxelib/polymod), and re-running hmm fixes the issue for me, and instead leads to a different issue. Still, past Polymod.

![image](https://github.com/FunkinCrew/Funkin/assets/69173292/95be3e77-6526-4ec9-98ff-3a61370d7761)

**Comment by EliteMasterEric** [comment] 2024-07-09 09:08
> Yeah that seemea to have fixed it! Your amazing!

Closing since OP had their issue resolve and everybody else replying simply didn't properly follow the compilation guide.

**Closed by EliteMasterEric** 2024-07-09 09:08 UTC
Labels: type: compilation help
