### ISSUE TITLE
 Crash Report: There is no asset library with an ID of "weekend1"

### ISSUE THREAD

**Issue by PedroSV2012** [FunkinCrew/Funkin#3461] opened 2024-09-26 18:37 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Steps to reproduce

1. Download the game 
2. Open the Game
3. Wait and there will be an popup saying: [lime.utils.Preloader] ERROR: There is  no asset library iwth an ID of "**weekend1**"

### Crash logs (can be found in the logs folder where Funkin.exe is)

There is no Crash log.. but the Crash Happen when closing the popup or pressing OK...

**Comment by Hundrec** [comment] 2024-09-26 18:40
This appears to be the same issue as this: https://github.com/FunkinCrew/Funkin/issues/3277

**Comment by PedroSV2012** [comment] 2024-09-26 18:47
the 2nd fix worked! thx!

**Comment by NotHyper-474** [comment] 2024-09-26 18:49
Since you managed to solve it and this is a duplicate of #3277 please close this.

**Closed** 2024-11-20 00:42 UTC
Labels: status: duplicate
