### ISSUE TITLE
Bug Report: Tracks restarting without any notes after playing through the song

### ISSUE THREAD

**Issue by ItzRonsku** [FunkinCrew/Funkin#3321] opened 2024-09-16 09:26 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Other (Specify below)

### Version

0.5.0

### Context (Provide images, videos, etc.)

After playing through one of the new songs, for example Philly Nice (Pico Mix) it restarts the song when it should close and bring up the results screen. When it restarts only the voices can be heard but not any notes appearin. This has happened quite frequently.
I'm using Opera GX and also google chrome and it still keeps happening on those browsers.
I could not provide a video example due to the file size being too big even though it was clipped to be as small as possible.

**Comment by AbnormalPoof** [comment] 2024-09-16 18:39
duplicate of #3142

**Comment by EliteMasterEric** [comment] 2024-09-17 08:14
Duplicate

**Closed by EliteMasterEric** 2024-09-17 08:14 UTC
Labels: status: duplicate
