### ISSUE TITLE
Bug Report: Chart Editor breaks PlayState.instance state

### ISSUE THREAD

**Issue by Starexify** [FunkinCrew/Funkin#3915] opened 2024-12-07 21:32 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.x

### Description (include any images, videos, errors, or crash logs)

When in ChartEditor, the PlayState.instance exists for first song , but when i return to chart editor the state becomes unusable in mods for some reason, for example when I set the State in:
function onSongLoaded(event:SongLoadScriptEvent)
and use onUpdate/onSongLoaded functions at the same time, the state isn't null for some reason and gives me errors such as "Null object reference" or just doesn't work and switches to vanilla fully.

Just example, but can try!
```haxe
import funkin.modding.module.Module;
import funkin.play.PlayState;

import flixel.FlxG;

import Std;

class Test extends Module {
    var loaded:Bool = false ;
    var state:PlayState;

    function new() {
        super("Test");
    }
    override function onSongLoaded(event:SongLoadScriptEvent) {
        super.onSongLoaded(event);
        if (!loaded) {
            state = PlayState.instance;
            state.playerStrumline.x = FlxG.width / 2 - state.playerStrumline.width / 2;
            state.opponentStrumline.visible = false;
            loaded = true;
        }
    }
    
    override function onSongEnd(event:ScriptEvent) { super.onSongEnd(event); loaded = false; }

    override function onSongRetry(event:ScriptEvent) { super.onSongRetry(event); }
    
     override function onStateChangeEnd(event:StateChangeScriptEvent) {
        if (!Std.isOfType(event.targetState, PlayState)) {
            loaded = false;
        }
    }
 }
```

I would appreciate help if there is a possibility to somehow add that "state.playerStrumline.x" work after returning in ChartEditor and playing the song again.
Thanks for your time !

### Steps to Reproduce

1. Open game with a mod like in the example above
2. See the state doesn't work anymore for some reason and the strumline , everything is no longer working

**Comment by KoloInDaCrib** [comment] 2024-12-07 21:42
PlayState is treated as a SubState when using the Chart Editor, so you should write a check for when that happens (via checking with `Std.isOfType`) and when it does use`FlxG.state.subState` instead

**Comment by Starexify** [comment] 2024-12-07 21:44
> PlayState is treated as a SubState when using the Chart Editor, so you should write a check for when that happens (via checking with `Std.isOfType`) and when it does use`FlxG.state.subState` instead
> 
> The parent state is the Chart Editor which doesn't have most of the things PlayState does

So like:
```
override function onStateChangeEnd(event:StateChangeScriptEvent) {
        if (!Std.isOfType(event.targetState, PlayState)) {
            loaded = false;
        }
        
         if (!Std.isOfType(event.targetState, ChartEditorState)) {
            state = FlxG.state.subState; 
        }
    }
```
or?

**Comment by KoloInDaCrib** [comment] 2024-12-07 21:47
> So like:
> 
> ```
> override function onStateChangeEnd(event:StateChangeScriptEvent) {
>         if (!Std.isOfType(event.targetState, PlayState)) {
>             loaded = false;
>         }
>         
>          if (!Std.isOfType(event.targetState, ChartEditorState)) {
>             state = FlxG.state.subState; 
>         }
>     }
> ```
> 
> or?

yeah something like that, if not I recommend tinkering around a bit more - either way it's not a bug and you may close the issue

**Closed** 2024-12-07 21:48 UTC
Labels: type: minor bug, status: pending triage
