### ISSUE TITLE
Bug Report: My game poster black boxes instead of boyfriend and girlfriend 

### ISSUE THREAD

**Issue by no-us** [FunkinCrew/Funkin#1021] opened 2021-05-04 17:33 UTC
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by VMGuy23** [comment] 2021-05-04 17:35
Memory issue, not game bug.

**Comment by no-us** [comment] 2021-05-04 17:41
> Memory issue, not game bug.

how to fix the bug and i play on newgrounds in qwant

**Comment by VMGuy23** [comment] 2021-05-04 17:44
You cant fix it, you dont have enough ram, only way to fix it is to get more ram

**Comment by VMGuy23** [comment] 2021-05-04 17:44
please close its not a bug

**Comment by NotHyper-474** [comment] 2021-05-07 18:12
There's the possibility that the game just loaded incorrectly, try clearing your browser's cache and see if it works

**Closed** 2024-05-08 07:00 UTC
Labels: legacy
