### ISSUE TITLE
BUG REPORT: MetaData window overlap in Chart Editor

### ISSUE THREAD

**Issue by JVNpixels** [FunkinCrew/Funkin#2841] opened 2024-06-17 19:04 UTC
## Describe the bug
There is a slight overlap in the MetaData window in the Chart Editor, and I can't click on certain drop down menus.

## To Reproduce
Open the MetaData window in the Chart Editor
## Expected behavior
It's kind of obvious, but it's not suppose to overlap

## Screenshots/Video
![screenshot-2024-06-17-11-53-50](https://github.com/FunkinCrew/Funkin/assets/146671762/742d0544-2926-4da2-bf07-aee944fae411)

## Desktop
 - OS:
Windows 11
 - Browser
I am on the Windows 11 build, but I use chrome.
 - Version:
v0.4.1

Slight Minor Bug.

**Comment by NotHyper-474** [comment] 2024-06-17 19:26
Duplicate of #2660

**Comment by Hundrec** [comment] 2024-10-01 07:54
This is now resolved as of 0.5.1
![image](https://github.com/user-attachments/assets/096e8c7e-2c0c-402a-8e71-2e6cda5a698b)

**Closed** 2024-10-02 00:16 UTC
Labels: status: pending triage
