### ISSUE TITLE
Bug Report: Whenever you play week 5 on NewGrounds it's INSANELY laggy. Please fix. Thx.

### ISSUE THREAD

**Issue by GregGamerGithub** [FunkinCrew/Funkin#272] opened 2021-01-24 04:19 UTC
# Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

### Web
- [Yes ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [ ] [Itch.io](https://ninja-muffin24.itch.io/funkin)

#### If you are using a web build, what browser are you using?
- [Yes ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
- [ ] Firefox, or a Gecko based broswer
- [ ] Safari
- [ ] Other, please specify:

### Local
- [ ] Windows x86
- [ ] Windows x86_64
- [ ] Linux
- [ ] macOS
- [ Yes] ChromeBook

**Comment by GregGamerGithub** [comment] 2021-01-24 04:22
yes
 pls fix

**Comment by regulad** [comment] 2021-01-24 14:30
Almost an exact duplicate of #247 and #244, just to name a few

**Comment by regulad** [comment] 2021-01-24 15:45
> 
> # Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.
> ## Where are you playing the game? NewGrounds
> ### Web
> 
>     * [Yes ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
> 
>     * [ ]  [Itch.io](https://ninja-muffin24.itch.io/funkin)
> 
> 
> #### If you are using a web build, what browser are you using?
> 
>     * [Yes ] Chrome, or a Chromium based broswer (Edge, Opera, etc.)
> 
>     * [ ]  Firefox, or a Gecko based broswer
> 
>     * [ ]  Safari
> 
>     * [ ]  Other, please specify:
> 
> 
> ### Local
> 
>     * [ ]  Windows x86
> 
>     * [ ]  Windows x86_64
> 
>     * [ ]  Linux
> 
>     * [ ]  macOS
> 
>     * [ Yes] ChromeBook
> 
> 
> ## What version of the game are you using? Look in the bottom left corner of the main menu. Latest update
> ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible. idk
> ## Please describe your issue. Provide extensive detail and images if possible. If you go to Week 5 On Friday Night Funkin it gets extremely laggy.

It doesn't look like you are running locally on a chromebook, you are running it in-broswer.

**Comment by GregGamerGithub** [comment] 2021-01-26 00:34
Hopefully ninjamuffin fixes it soon.

**Closed** 2024-05-08 07:06 UTC
Labels: legacy
