### ISSUE TITLE
Bug Report: Notes can be pressed during week 3 pico mix cutscene

### ISSUE THREAD

**Issue by Itsgithubfellow** [FunkinCrew/Funkin#3219] opened 2024-09-13 20:40 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When loading into Pico, Philly Nice, or Blammed with playable pico, you can miss notes and cause a game over, which bugs out the whole sequence and keeps playing the cutscene in the background, causing a crash.

### Steps to reproduce (or crash logs, errors, etc.)

Go into any Pico song as pico
Spam notes during the cutscene

**Comment by GoombarioFan** [comment] 2024-09-14 07:18
Seems to be a duplicate of #3181, though this report has a better title

**Comment by EliteMasterEric** [comment] 2024-09-16 20:46
Duplicate of #3146

**Closed by EliteMasterEric** 2024-09-16 20:46 UTC
Labels: status: duplicate
