### ISSUE TITLE
Bug Report: Pressing the R key during Week 6 dialouge crashes the game.

### ISSUE THREAD

**Issue by MasterGamingYT** [FunkinCrew/Funkin#659] opened 2021-03-26 17:18 UTC
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
https://ninja-muffin24.itch.io/funkin
### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chrome
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.7.1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
Open week 6
Press R during a text box
crash

## Please describe your issue. Provide extensive detail and images if possible.
During a text box sequence, when I press the insta-death key (R), the game locks up entirely and the only way to bring it back is to close the window

**Comment by OPNA2608** [comment] 2021-03-29 12:45
Duplicate of #313.

**Closed** 2024-05-08 07:03 UTC
Labels: legacy
