### ISSUE TITLE
Bug Report: Blazin' text is broken in freeplay menu.

### ISSUE THREAD

**Issue by SnowyyWHY** [FunkinCrew/Funkin#2887] opened 2024-06-22 22:19 UTC
When I enter the freeplay menu, everything works fine, but if i go to blazin' and enter and leave it, the text of Blazin' becomes flattened for some reason, here's a   ##screenshot:
![obraz_2024-06-23_001826400](https://github.com/FunkinCrew/Funkin/assets/134156720/fc248b6a-1fe4-4fb5-a8a2-97eff134dfac)

**Comment by Hundrec** [comment] 2024-06-22 22:25
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2659, but adds Blazin' to the list.

**Closed** 2024-06-24 17:38 UTC
Labels: status: duplicate
