### ISSUE TITLE
Bug Report: Pico Death Screen is Broken if we restart it on Week 3

### ISSUE THREAD

**Issue by LokiTheDevCat** [FunkinCrew/Funkin#3346] opened 2024-09-17 09:56 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Opera

### Version

0.5.0

### Context (Provide images, videos, etc.)

In Week 3 playing as Pico, if we restart on Cutscene, the Death Screen will be broken, and the music starts but the cutscene is still playing

### Steps to reproduce (or crash logs, errors, etc.)

Go on Week 3 with Pico and press "R"

**Comment by EliteMasterEric** [comment] 2024-09-18 08:02
This is related to restarting during the cutscene

Duplicate of #3146

**Closed by EliteMasterEric** 2024-09-18 08:02 UTC
Labels: status: duplicate

**Comment by LokiTheDevCat** [comment] 2024-09-18 09:48
> This is related to restarting during the cutscene
> 
> Duplicate of #3146

Oh, I didn't noticed that
