### ISSUE TITLE
Bug Report: Pico missing in Weekend 1 

### ISSUE THREAD

**Issue by Rorriis** [FunkinCrew/Funkin#2507] opened 2024-05-14 17:41 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as clearing cookies, clearing AppData, trying another browser) before submitting an issue.

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] Windows
- [ ] Mac
- [X] Linux

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

0.3.2, with hxCodex fix to build

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

You pick Darnell, Lit up or 2hot and then look at the lack of Pico on screen
 
## Please describe your issue. Provide extensive detail and images if possible.

He's just replaced with the Haxe logo 

![image](https://github.com/FunkinCrew/Funkin/assets/97610612/b54047eb-81da-4d3e-96b0-fe714a504595)

Terminal log
```
source/funkin/play/character/CharacterData.hx:252: Successfully instantiated character (stable): pico-playable
source/funkin/play/character/MultiSparrowCharacter.hx:29: Creating Multi-Sparrow character: pico-playable
source/funkin/play/character/MultiSparrowCharacter.hx:71: Creating multi-sparrow atlas: characters/Pico_Basic
source/funkin/play/character/MultiSparrowCharacter.hx:82: Multi-Sparrow atlas could not load subtexture: characters/pico-hey
source/funkin/modding/PolymodErrorHandler.hx:84: [ERROR] Error while executing function PicoPlayerCharacter.onCreate()#26: 
An unknown error occurred: hscriptClass(assets/scripts/characters/pico-playable.hxc):26: Script threw an exception: 
Null Object Reference
```

**Comment by Eerorri** [comment] 2024-05-14 20:49
duplicate of #2384 
i should look through these issues better

**Closed by Eerorri** 2024-05-14 20:49 UTC
Labels: type: minor bug
