### ISSUE TITLE
Enhancement: The ability to play BF Instrumentals in Pico Remixes

### ISSUE THREAD

**Issue by epokgamr** [FunkinCrew/Funkin#3744] opened 2024-10-20 14:30 UTC
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

we can do pico instrumentals in bf songs why not the opposite for pico?

**Comment by AbnormalPoof** [comment] 2024-10-20 15:35
Duplicate of #3204

**Comment by JVNpixels** [comment] 2024-10-20 18:43
Please close this issue by clicking the purple checkmark button, this has already been reported so there is no need to make another request for this!

**Closed** 2024-12-02 21:12 UTC
Labels: status: duplicate
