### ISSUE TITLE
Bug Report: Spirit's Afterimages are Broken

### ISSUE THREAD

**Issue by BenjaminTheHedgefox** [FunkinCrew/Funkin#3373] opened 2024-09-18 16:47 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

Spirit's afterimages don't follow his position and offsets properly anymore.

![Screenshot 2024-09-19 023031](https://github.com/user-attachments/assets/ae4e1e16-59c0-46d2-9b8c-8b136aa98da0)

It's been like this ever since 0.5.0 released, and the previous version of the game I've got handy (0.4.1) doesn't have this bug.

![image](https://github.com/user-attachments/assets/b71e1bba-ce12-4453-97b0-b9e8f019ea55)

It's definitely an odd issue, I'll give it that.

### Steps to reproduce (or crash logs, errors, etc.)

Play Thorns and watch the mess that ensues.

**Comment by NotHyper-474** [comment] 2024-09-18 16:54
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3144

**Comment by BenjaminTheHedgefox** [comment] 2024-09-18 16:56
Dang, I keep missing these things! I'll try and be more diligent before filing an issue.

**Comment by BenjaminTheHedgefox** [comment] 2024-09-18 16:57
(i don't know how to close it without being completed closed lmao)

**Closed** 2024-09-18 16:56 UTC
Labels: status: duplicate
