### ISSUE TITLE
Compiling help: Multiple errors when compiling

### ISSUE THREAD

**Issue by MulakkJ** [FunkinCrew/Funkin#2402] opened 2024-05-09 12:35 UTC
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

so i had a problem with funkin.vis.dsp.SpectralAnalyzer but removed and reinstalled funkin.vis and it stopped the error
![eazeazezaeaz](https://github.com/FunkinCrew/Funkin/assets/112482666/fc8e2b56-82fe-4715-9392-391ddd3edb2c)

but now i have more problems, its probably cuz i forgot to install some things or smth like that
![329241250-7c9d710d-a183-4f78-92d3-2125e092fc81](https://github.com/FunkinCrew/Funkin/assets/112482666/c18a5f32-d862-4074-8e3b-258d7053ec97)

would be pretty cool if someone knows what i should do

**Comment by NotHyper-474** [comment] 2024-05-09 12:42
Duplicate of https://github.com/FunkinCrew/Funkin/issues/2392

**Closed** 2024-05-09 12:42 UTC
Labels: status: duplicate

**Comment by ADuckInBlack** [comment] 2024-05-09 22:23
if i end up solving my problem, i'll tell you about it

**Comment by MulakkJ** [comment] 2024-05-10 18:50
nahhh is good now i got another problem
