### ISSUE TITLE
Bug Report: going to the title screen locks pico

### ISSUE THREAD

**Issue by ninjarecroomyt** [FunkinCrew/Funkin#3237] opened 2024-09-14 00:05 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5

### Context (Provide images, videos, etc.)

when u go to the title screen pico gets locked again you can still play as him you just have to watch the unlock cutscene again

### Steps to reproduce (or crash logs, errors, etc.)

unlock pico go to title screen than go back to freeplay menu and u should see thats hes locked again and u have to watch the cutscene again

**Comment by AbnormalPoof** [comment] 2024-09-14 00:06
Duplicate of #3165

**Comment by EliteMasterEric** [comment] 2024-09-15 00:30
Confirmed duplicate of #3165

**Closed by EliteMasterEric** 2024-09-15 00:30 UTC
Labels: status: duplicate
