### ISSUE TITLE
Bug Report: Pico's score on Darnell was showing on Darnell Bf mix

### ISSUE THREAD

**Issue by Charlemack** [FunkinCrew/Funkin#3425] opened 2024-09-22 05:54 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

5.0

### Context (Provide images, videos, etc.)

My score for "Darnell" when playing as Pico was also showing on "Darnell BF Mix". I have a 97% on Darnell as Pico and a 100% on Darnell as Boyfriend, but 97% was showing when I was Boyfriend.

**Comment by Hundrec** [comment] 2024-09-22 06:07
This is a duplicate of https://github.com/FunkinCrew/Funkin/issues/3145

**Comment by EliteMasterEric** [comment] 2024-09-22 13:46
Duplicate

**Closed by EliteMasterEric** 2024-09-22 13:46 UTC
Labels: status: duplicate
