### ISSUE TITLE
Crash Report: Pressing R during the Pico cutscene and restarting crashes the game

### ISSUE THREAD

**Issue by MrMooey** [FunkinCrew/Funkin#3275] opened 2024-09-14 19:22 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide screenshots or videos of the crash happening)

While playing as Pico and playing any of the week 3 songs, you can press R during the intro cutscene and retry multiple times. This visually duplicates the characters and once the cutscene ends, the game freezes up completely and needs to be forcefully closed.

Here's footage of me dying twice and then letting the cutscene play out
https://github.com/user-attachments/assets/90cf2e45-7645-4f3a-933e-ad56e0533e5c

Here's footage of me dying a lot more before letting the cutscene play out
https://github.com/user-attachments/assets/54f93687-776c-4e8b-9d3e-88705ac89e79

I think an easy way to fix this is just to disable R during cutscenes so this doesn't happen

### Steps to reproduce

1. Play as Pico
2. Play any Week 3 (Pico Mix) song
3. While the cutscene is playing, press R to die
4. Restart and let the cutscene play out

### Crash logs (can be found in the logs folder where Funkin.exe is)

Here's my crash log:
[crash-2024-09-14-15-03-33.log](https://github.com/user-attachments/files/17003543/crash-2024-09-14-15-03-33.log)

**Comment by Darkness8374939** [comment] 2024-09-14 22:41
I experienced this too, but while pressing the arrow keys.

**Comment by EliteMasterEric** [comment] 2024-09-16 20:45
Duplicate of #3146

**Closed by EliteMasterEric** 2024-09-16 20:45 UTC
Labels: status: duplicate
