### ISSUE TITLE
Bug Report: Note splashes from week 6 are gone

### ISSUE THREAD

**Issue by JackXson-Real** [FunkinCrew/Funkin#2389] opened 2024-05-09 04:52 UTC
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

[weed]: <> (ALSO MAKE SURE THAT YOU USE PROPER LABELS, IF YOU'RE RUNNING INTO COMPILER ISSUES, USE THE compiler issue LABEL!!!)

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)
0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Play week 6 and press notes, you will see no note splashes

## Please describe your issue. Provide extensive detail and images if possible.
Note splashes from week 6 are gone. They used to be in 0.2.8 (screenshot below) but now they are gone. I'm assuming they are temporarily removed so that the sprites could be redone, but I am making this report just in case it is not intentional and is a bug.

Here is what it is supposed to look like (screenshot from version 0.2.8):
![vlcsnap-2024-05-09-00h48m37s763](https://github.com/FunkinCrew/Funkin/assets/32755192/cdf45cb5-b89b-4d84-a7f8-9d47caf18dee)

**Comment by moxie-coder** [comment] 2024-05-09 05:18
don’t make duplicate issues dude

**Comment by EliteMasterEric** [comment] 2024-05-09 05:33
Duplicate of #2338.

**Closed by EliteMasterEric** 2024-05-09 05:33 UTC
Labels: status: duplicate

**Comment by moxie-coder** [comment] 2024-05-09 05:41
> Duplicate of #2338.

thank you eric

**Comment by JackXson-Real** [comment] 2024-05-09 07:11
> don’t make duplicate issues dude #2338

lol mb forgot to look for that was in a rush 💀
