### ISSUE TITLE
week 6 bug

### ISSUE THREAD

**Issue by JustAMicrowave** [FunkinCrew/Funkin#338] opened 2021-02-03 13:41 UTC
so on both downloaded and newgrounds version the game will crash. It will happen if you hit r to kill the boyfriend during a cutscene. I haven't tried it in week 5 during lights off, but i don't think it happens then. Not a major game breaking bug, but a bg none the less. The whole game will close in the download and it will freeze on new grounds. I can't attach a video file but by pressing r during a cutscene (or dialogue. basically in between any of the senpai's phases) the game will crash. Even during the transformation cutscene in week 6.

**Comment by ActualMandM** [comment] 2021-02-03 18:26
Duplicate of #313

**Closed** 2024-05-08 07:06 UTC
Labels: legacy
