### ISSUE TITLE
Bug Report: Songs Completely Die Because Of Custom Input Offset Value

### ISSUE THREAD

**Issue by floofycatto** [FunkinCrew/Funkin#3684] opened 2024-10-13 05:28 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Microsoft Edge

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

I have a custom offset value of 70 and noticed that on the newgrounds version of the game and windows this happens, when setting my offset to 0 it plays normally (it's still a little laggy tho idk why) 
https://github.com/user-attachments/assets/c2c80965-db5c-42c0-be5d-e64a4dc77c72

### Steps to Reproduce

Change the offset value to I'm assuming anything but default

**Comment by AbnormalPoof** [comment] 2024-10-13 05:32
Duplicate of #3380 #3495 and #3667

**Comment by NotHyper-474** [comment] 2024-10-13 05:34
Already solved in 0.5.2

**Closed** 2024-10-16 21:07 UTC
Labels: status: duplicate
