### ISSUE TITLE
Bug Report: I Can't continue week 2!

### ISSUE THREAD

**Issue by CodeMaster1976** [FunkinCrew/Funkin#3854] opened 2024-11-11 23:02 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Opera

### Version

0.5.2

### Description (include any images, videos, errors, or crash logs)

When i was playing the game, it would **not let me past song 1 of week 2**, can you fix that as it just plays the song again with no arrows!

### Steps to Reproduce

1. Go to story mode
2. Enter week 2 on hard
3. Play the first song
Done: You can see what happens...

**Comment by AbnormalPoof** [comment] 2024-11-11 23:04
Duplicate of #3142

**Comment by Hundrec** [comment] 2024-11-12 00:46
Please close this issue since it's a duplicate. You can find previous discussion of this bug in the issue linked above.

**Closed** 2024-11-18 23:17 UTC
Labels: type: minor bug, status: duplicate
