### ISSUE TITLE
Polymod Script Exception

### ISSUE THREAD

**Issue by floofycatto** [FunkinCrew/Funkin#3166] opened 2024-09-13 04:57 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I was just playing the game as usual, finished all of pico's songs, noticed I could play the weeks with the pico instrumentals, then played blammed with bf and this showed up, I think this also caused the 2nd image, I tried to recreate the situation but it didn't work, so pretty weird bug

![image](https://github.com/user-attachments/assets/4ed2765d-7013-4209-8101-db96db613fbd)
![image](https://github.com/user-attachments/assets/fefc6d51-5b88-4add-b569-5620851fcc49)

**Comment by EliteMasterEric** [comment] 2024-09-17 02:00
Duplicate of #3143

**Closed by EliteMasterEric** 2024-09-17 02:00 UTC
Labels: status: duplicate
