### ISSUE TITLE
Bug Report: Pico unlocked without save data

### ISSUE THREAD

**Issue by biomseed** [FunkinCrew/Funkin#3352] opened 2024-09-17 22:20 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5.0

### Context (Provide images, videos, etc.)

In the web version where I (at least seemingly) have no save data, the face bf makes when pico is unlocked is shown in freeplay. 

### Steps to reproduce (or crash logs, errors, etc.)

Play the game or something idk

**Comment by AbnormalPoof** [comment] 2024-09-17 22:29
Duplicate of #3294

**Comment by EliteMasterEric** [comment] 2024-09-18 07:24
Duplicate

**Closed by EliteMasterEric** 2024-09-18 07:24 UTC
Labels: status: duplicate
