### ISSUE TITLE
Bug Report: Everytime i start up the game it keeps asking me to unlock pico when i already did

### ISSUE THREAD

**Issue by alightFNF** [FunkinCrew/Funkin#3421] opened 2024-09-21 17:41 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

I was recording fnf for a video and i unlocked pico after going to freeplay. cool! i played pico (pico mix) and after the song ended, it replayed but nothing happened. just two pico's boppin' their heads to the music i guess. i thought it was a glitch since this WAS my first time using the download and that seems to happen to me sometimes so i re-opened it. i went to freeplay again, and bf was doing the same glowy eyes kinda animation and the text in the background said what it said on my first time opening the file...i thought maybe its another glitch but it made me unlock pico again? issss this normal? cuz i have content to make.

**Comment by AbnormalPoof** [comment] 2024-09-21 17:43
Duplicate of #3165.

**Comment by alightFNF** [comment] 2024-09-21 18:32
> Duplicate of #3165.

oh ok thx

**Comment by JVNpixels** [comment] 2024-09-21 19:00
Close this please! Thank you!

**Closed** 2024-09-21 19:10 UTC
Labels: status: duplicate
