### ISSUE TITLE
Bug Report: Game stops responding when exiting on title screen

### ISSUE THREAD

**Issue by amyspark-ng** [FunkinCrew/Funkin#3387] opened 2024-09-19 16:44 UTC
### Issue Checklist

- [X] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.0

### Context (Provide images, videos, etc.)

When i press escape on the title screen the game becomes unresponsive causing it not to exit 

### Steps to reproduce (or crash logs, errors, etc.)

1. Press ESC on the title screen

**Comment by NotHyper-474** [comment] 2024-09-19 17:21
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3196

**Comment by amyspark-ng** [comment] 2024-09-19 17:59
oh sorry

**Closed** 2024-09-19 17:59 UTC
Labels: status: duplicate
