### ISSUE TITLE
Bug Report: Hold note cover stays after lag spike

### ISSUE THREAD

**Issue by SEBBY180** [FunkinCrew/Funkin#3612] opened 2024-10-07 16:48 UTC
### Issue Checklist

- [ ] I have properly named my issue
- [ ] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

![screenshot-2024-10-07-12-45-43](https://github.com/user-attachments/assets/fea9f2e5-c4c8-4a46-a58c-43b343b4d03c)
If the game lags while hitting a hold note, the hold note cover stays on the arrow for the rest of the song.

**Comment by AbnormalPoof** [comment] 2024-10-07 16:49
Duplicate of #3280.

**Comment by SEBBY180** [comment] 2024-10-07 16:53
> Duplicate of #3280.

Oh. Didn't realize this was already reported. My bad.

**Comment by AbnormalPoof** [comment] 2024-10-07 16:56
No worries! Please close the issue using the purple checkmark button at the bottom.
![Screenshot 2024-10-07 at 11 56 30 AM](https://github.com/user-attachments/assets/a84ce000-e08e-4237-8b71-8b9f72a871df)

**Closed** 2024-10-07 16:57 UTC
Labels: status: duplicate
