### ISSUE TITLE
Bug Report: Literally all Pico remixes are just gone now. BF remix of Darnell is also missing.

### ISSUE THREAD

**Issue by macmacfire** [FunkinCrew/Funkin#3604] opened 2024-10-06 19:11 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Newgrounds (Web/HTML5)

### Browser

Firefox

### Version

0.5.1

### Description (include any images, videos, errors, or crash logs)

Surprised to see this hasn't been reported, as the Newgrounds comments suggest it isn't just me. Self-explanatory title - Pico remixes in freeplay are suddenly unavailable. Kinda big considering that's, like, the entire point of this recent update.

**Comment by AbnormalPoof** [comment] 2024-10-06 19:19
Duplicate of #3487.

**Comment by macmacfire** [comment] 2024-10-06 20:01
> Duplicate of #3487.

Ah, knew I'd end up just making a duplicate. Dunno how I didn't see it when I checked...Ah well, it is pretty big still, lel.

**Comment by Hundrec** [comment] 2024-10-06 20:27
Please close this issue using the purple checkmark button.

**Closed** 2024-10-06 21:19 UTC
Labels: status: duplicate
