### ISSUE TITLE
Crash Report: Stage Editor Create Object Shader Crash

### ISSUE THREAD

**Issue by sphis-Sinco** [FunkinCrew/Funkin#3859] opened 2024-11-13 22:26 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

Other (Specify in Description field)

### Version

0.5.3

### Description

I was trying to make a stage with the stage editor and I just tried to create an object.

### Steps to Reproduce

1) Go to stage editor
2) Create blank stage
3) go to edit > new object
4) name your object
5) shader crash

### Crash logs

Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 26
Called from ApplicationMain::create ApplicationMain.hx line 137
Called from openfl.display.Application::exec openfl/display/Application.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 151
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 147
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 384
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 2213
Called from openfl.display.Stage::__render openfl/display/Stage.hx line 2132
Called from openfl.display.OpenGLRenderer::__render openfl/display/OpenGLRenderer.hx line 771
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 31
Called from openfl.display.OpenGLRenderer::__renderDrawable openfl/display/OpenGLRenderer.hx line 864
Called from openfl.display._internal.Context3DDisplayObjectContainer::renderDrawable openfl/display/_internal/Context3DDisplayObjectContainer.hx line 18
Called from openfl.display._internal.Context3DDisplayObject::renderDrawable openfl/display/_internal/Context3DDisplayObject.hx line 69
Called from openfl.display._internal.Context3DShape::render openfl/display/_internal/Context3DShape.hx line 39
Called from openfl.display._internal.Context3DGraphics::render openfl/display/_internal/Context3DGraphics.hx line 612
Called from openfl.display.OpenGLRenderer::__initShaderBuffer openfl/display/OpenGLRenderer.hx line 590
Called from openfl.display.OpenGLRenderer::__initGraphicsShader openfl/display/OpenGLRenderer.hx line 576
Called from openfl.display.Shader::__init openfl/display/Shader.hx line 550
Called from openfl.display.Shader::__initGL openfl/display/Shader.hx line 622
Called from openfl.display.Shader::__createGLProgram openfl/display/Shader.hx line 437
Called from openfl.display.Shader::__createGLShader openfl/display/Shader.hx line 425
Called from lime.utils.Log::error lime/utils/Log.hx line 37

**Comment by NotHyper-474** [comment] 2024-11-14 01:14
Duplicate of https://github.com/FunkinCrew/Funkin/issues/3705

**Closed** 2024-11-18 23:16 UTC
Labels: status: duplicate, type: major bug
