### ISSUE TITLE
Squished text ensues in Freeplay menu capsules

### ISSUE THREAD

**Issue by rrev07** [FunkinCrew/Funkin#2784] opened 2024-06-13 09:04 UTC
\[title explains itself\] , v0.4.1

![image](https://uploads.linear.app/b9f0050d-7020-42ad-9d4b-7551ff30d00f/bb897c63-e035-4af5-8cbe-79c2256de354/85103556-b7e5-4570-8346-36e675abb8a8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2I5ZjAwNTBkLTcwMjAtNDJhZC05ZDRiLTc1NTFmZjMwZDAwZi9iYjg5N2M2My1lMDM1LTRhZjUtOGNiZS03OWMyMjU2ZGUzNTQvODUxMDM1NTYtYjdlNS00NTcwLTgzNDYtMzZlNjc1YWJiOGE4IiwiaWF0IjoxNzE4NDMxNDIyLCJleHAiOjMzMjg4OTkxNDIyfQ.4u3QhgjitCPTHepVkvDLHesTQ69IMHd9wpNvcNEPP7c)

**Comment by Hundrec** [comment] 2024-06-13 18:27
Also reported in #2659, #2682, and #2703

This report confirms that this bug still happens in v0.4.1

**Comment by EliteMasterEric** [comment] 2024-06-17 02:53
Duplicate of #2659.

**Closed by EliteMasterEric** 2024-06-17 02:53 UTC
Labels: status: duplicate
