### ISSUE TITLE
Bug Report: Error in animation editor window

### ISSUE THREAD

**Issue by Damianeitor** [FunkinCrew/Funkin#3494] opened 2024-09-30 19:46 UTC
### Issue Checklist

- [X] I have properly named the issue
- [x] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

0.5.1

### Context (Provide images, videos, etc.)

In the animation editor, the window that allows you to change characters and gives you the keys does not open.

**Comment by CrusherNotDrip** [comment] 2024-09-30 19:52
Duplicate of #3151

**Comment by EliteMasterEric** [comment] 2024-10-02 05:59
Duplicate

**Closed by EliteMasterEric** 2024-10-02 05:59 UTC
Labels: status: duplicate
