### ISSUE TITLE
when I go into the "freeplay" menu it bugs out and I get an error message 

### ISSUE THREAD

**Issue by tacomygingercat** [FunkinCrew/Funkin#2270] opened 2024-05-04 05:46 UTC
[weed]: <> 
![Capture](https://github.com/FunkinCrew/Funkin/assets/168889107/00f8944d-c3a7-4964-bd2c-ef47e3107b73)

[weed]: <> I don't really have any more info to give. sorry
[weed]: <> all it says is just like I guess I did give a screenshot so just look at that to
[weed]: <> fix the problem y'know I just don't know what to say guess that's it
[weed]: <> also I'm on the pc app for this bug

### If you are playing the game in a browser, what site are you playing it from?

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [x] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

[weed]: <> (Again, put an x in the [ ] box!)

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

I'm not playing it on a browser 

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

v0.3.2

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

here's the error missing 

![Capture](https://github.com/FunkinCrew/Funkin/assets/168889107/1a07f444-d17a-4bb9-a1ab-a13cc16c5b99)

## Please describe your issue. Provide extensive detail and images if possible.

ermm again here's the image

![Capture](https://github.com/FunkinCrew/Funkin/assets/168889107/a63b6bb3-840c-49db-b3a1-dad1596e6194)

**Comment by SilverT4** [comment] 2024-05-04 06:21
[This appears to be a common issue with AMD GPUs not playing nicely with shaders on Haxe](https://twitter.com/DiomaFX/status/1785508662469136856) (which FNF runs on)

**Comment by EliteMasterEric** [comment] 2024-05-08 17:50
Duplicate of #2220.

**Closed by EliteMasterEric** 2024-05-08 17:50 UTC
Labels: status: duplicate
