### ISSUE TITLE
Bug Report: freeplay crashes everytime i open it.

### ISSUE THREAD

**Issue by hfgdhfhfhs** [FunkinCrew/Funkin#2247] opened 2024-05-02 01:34 UTC
![imagem_2024-05-01_223352577](https://github.com/FunkinCrew/Funkin/assets/168694704/3b9c1b1e-301c-4465-a707-5d7c5375acd7)
i was trying to play the erect songs but then this error showed up, shader thing i need help. :(

**Comment by biomseed** [comment] 2024-05-02 20:39
Update your graphics drivers and see if that helps, a lot of people have had this issue

**Comment by hfgdhfhfhs** [comment] 2024-05-04 14:47
didnt work :C

**Comment by EliteMasterEric** [comment] 2024-05-08 17:50
Duplicate of #2220.

**Closed by EliteMasterEric** 2024-05-08 17:50 UTC
Labels: status: duplicate
