### ISSUE TITLE
Black screen in the 32 bits version

### ISSUE THREAD

**Issue by Cristo0AC** [FunkinCrew/Funkin#281] opened 2021-01-25 21:30 UTC
Hello
I'm using my netbook with Windows 7 32 bits, and i only hear the sound.
I can press Enter and navigate in the menu, but i can see nothing.
I leave screenshots.
![Sin título](https://user-images.githubusercontent.com/71469767/105768089-a3749300-5f3a-11eb-8a7b-5ab50c6f1819.jpg)
![Sin título 2](https://user-images.githubusercontent.com/71469767/105768590-58a74b00-5f3b-11eb-9972-5f8e8ef54888.jpg)

**Comment by regulad** [comment] 2021-01-25 21:31
Duplicate of #275.

**Comment by Geekume** [comment] 2021-01-26 01:10
hey! at least you got to the HaxeFlixel logo kudos

**Closed** 2024-05-08 07:06 UTC
Labels: legacy
