### ISSUE TITLE
Game audio breaks after switching audio devices

### ISSUE THREAD

**Issue by spark-the-dragon** [FunkinCrew/Funkin#2606] opened 2024-05-25 03:06 UTC
### If you are playing the game in a browser, what site are you playing it from?

- [ ] [Newgrounds](https://www.newgrounds.com/portal/view/770371)
- [X] [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below
- 
  - [X] Windows
- 
  - [ ] Mac
- 
  - [ ] Linux

### If you are playing the game in a browser, what browser are you using?

- [ ] Google Chrome (or chomium based like Brave, vivaldi, MS Edge)
- [ ] Firefox
- [ ] Safari

## What version of the game are you using? Look in the bottom left corner of the main menu. (ex: 0.2.7, 0.2.1, shit like that)

3.3

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Be connected to a bluetooth speaker or earbuds, and play the game, and then eventually turn off the bluetooth device and use your normal audio speaker in your computer

## Please describe your issue. Provide extensive detail and images if possible.

upon turning off a bluetooth audio device and using your normal speakers, the game will not recognize the change and wont switch to your current audio device until you restart the game. This also causes a problem in songs as when you load into a song, after go, all the notes disappear and the characters stop bopping too, this is only fixed after restarting the game. There is a video showing the bug

[https://github.com/FunkinCrew/Funkin/assets/125839215/35987782-55eb-4cda-b606-809af03f87ba](https://github.com/FunkinCrew/Funkin/assets/125839215/35987782-55eb-4cda-b606-809af03f87ba)

## If you're game is FROZEN and you're playing a web version, press F12 to open up browser dev window, and go to console, and copy-paste whatever red error you're getting

**Comment by JackXson-Real** [comment] 2024-05-25 17:39
I’ve had this issue too, it’s very annoying.

**Comment by gamerbross** [comment] 2024-05-25 19:50
yeah, this happends when you switch audio device. I hope gets fixed (Codename Engine did it, so at least we know its possible to fix)

**Comment by NotHyper-474** [comment] 2024-10-04 22:15
Turns out this was a duplicate of #2286 all along

**Comment by EliteMasterEric** [comment] 2024-10-07 22:05
Technically #2264 is a different issue. This is a duplicate of #2285 though.

**Closed** 2024-10-07 22:05 UTC
Labels: status: duplicate
