### ISSUE TITLE
Bug Report: Darnell (BF MIX) is straight up inaccessible, Weekend 1 songs require turning page to find

### ISSUE THREAD

**Issue by TorchBloom** [FunkinCrew/Funkin#3628] opened 2024-10-09 15:55 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

Google Chrome

### Version

v0.5.1

### Description (include any images, videos, errors, or crash logs)

1: Darnell (BF MIX) is missing from freeplay, I tried replaying weekend 1 to potentially re unlock it, but nothing, it is not possible to play it at all.
![image](https://github.com/user-attachments/assets/80710ae3-cf4f-4b7e-bc38-3af12845328f)
2: In Pico's Freeplay, His mixes are now SEPERATE from the weekend 1 songs for some odd reason. Loading into Pico's menu presents you with the weekend 1 songs with the other mixes nowhere to be seen, its only by turning to page (while hovering over random only) as if u were switching to erect mode would you find the other songs, this creates the issue where an average person wouldn't be able to find any of the pico mixes available.
![image](https://github.com/user-attachments/assets/c083e5b2-3d42-4106-baa8-037ec2bcf1e3)
![image](https://github.com/user-attachments/assets/5571cb32-80dd-4418-92b3-ed2c319a9c62)

### Steps to Reproduce

1: Open game
2: Look for Darnell (BF MIX) its just gone and inaccessible
3: Switch to Pico
4: Hover over random in his freeplay menu since you can only see darnell's tracks on screen and turn the page to find the others.

**Comment by AbnormalPoof** [comment] 2024-10-09 15:56
Duplicate of #3487

**Comment by biomseed** [comment] 2024-10-09 21:26
PLease close this. Also, you can access it. Just press a direction on "Random" over and over.

**Closed** 2024-10-20 05:53 UTC
Labels: status: duplicate
