### ISSUE TITLE
Crash Report: Ploy mod script exception

### ISSUE THREAD

**Issue by PureEcstasy** [FunkinCrew/Funkin#3611] opened 2024-10-07 15:21 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

Microsoft Edge

### Version

v0.5.1

### Description

Pico remixes missing, plus ploymod script errors. 

### Steps to Reproduce

Simply open up the game. then go to Pico and if all you see are thhe Darnell remixes, click on one and it will repeat itself on either the first or second note of the opposing side

### Crash logs

Funkin Crash Report
=====================

Generated by: Friday Night Funkin' - v0.5.1
  Git hash: 0971a0b (CLEAN)
System timestamp: 2024-10-07-16-41-30
Driver info: OpenGL Vendor=Intel Version=4.6.0 - Build 30.0.101.1404 Renderer=Intel(R) UHD Graphics GLSL=4.60 - Build 30.0.101.1404
Platform: Windows
Render method: DRAW_TILES

=====================

HXCPP-Immix:
- Memory Used: 1786509784 bytes
- Memory Reserved: 2029920344 bytes
- Memory Current Pool: 1786511832 bytes
- Memory Large Pool: 1739653208 bytes
- HXCPP Debugger: Disabled
- HXCPP Exp Generational Mode: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Exp Moving GC: Disabled
- HXCPP Debug Link: Disabled
- HXCPP Stack Trace: Enabled
- HXCPP Stack Trace Line Numbers: Enabled
- HXCPP Pointer Validation: Enabled
- HXCPP Profiler: Disabled
- HXCPP Local Telemetry: Disabled
- HXCPP C++11: Disabled
- Source Annotation: Disabled

=====================

Flixel Current State: funkin.play.PlayState

=====================

Haxelibs: 
- FlxPartialSound git(https://github.com/FunkinCrew/FlxPartialSound.git/:a1eab7b9bf507b87200a3341719054fe427f3b15
- flixel git(https://github.com/FunkinCrew/flixel/:f2b090d6c608471e730b051c8ee22b8b378964b1
- flixel-addons git(https://github.com/FunkinCrew/flixel-addons/:7424db4e9164ff46f224a7c47de1b732d2542dd7
- flixel-text-input git(https://github.com/FunkinCrew/flixel-text-input/:951a0103a17bfa55eed86703ce50b4fb0d7590bc
- flxanimate git(https://github.com/Dot-Stuff/flxanimate/:0654797e5eb7cd7de0c1b2dbaa1efe5a1e1d9412
- format haxelib(3.5.0)
- funkin.vis git(https://github.com/FunkinCrew/funkVis/:22b1ce089dd924f15cdc4632397ef3504d464e90
- grig.audio git(https://gitlab.com/haxe-grig/grig.audio.git/src:57f5d47f2533fd0c3dcd025a86cb86c0dfa0b6d2
- hamcrest haxelib(3.0.0)
- haxeui-core git(https://github.com/haxeui/haxeui-core/:c9d96b168ea2a19274ad7c766ab1a34b57baa793
- haxeui-flixel git(https://github.com/haxeui/haxeui-flixel/:013b9d4e56bfe9a034e028a8d685f0b274cb73c4
- hscript git(https://github.com/FunkinCrew/hscript/:12785398e2f07082f05034cb580682e5671442a2
- hxCodec git(https://github.com/FunkinCrew/hxCodec/:61b98a7a353b7f529a8fec84ed9afc919a2dffdd
- hxcpp git(https://github.com/cortex-engine/hxcpp/:c6bac3d6c7d683f25104296b2f4c50f8c90b8349
- hxcpp-debug-server git(https://github.com/FunkinCrew/hxcpp-debugger/hxcpp-debug-server:147294123f983e35f50a966741474438069a7a8f
- hxdiscord_rpc git(https://github.com/FunkinCrew/hxdiscord_rpc/:82c47ecc1a454b7dd644e4fcac7e91155f176dec
- hxjsonast git(https://github.com/nadako/hxjsonast//:20e72cc68c823496359775ac1f06500e67f189d5
- hxp haxelib(1.3.0)
- json2object git(https://github.com/FunkinCrew/json2object/:a8c26f18463c98da32f744c214fe02273e1823fa
- jsonpatch git(https://github.com/EliteMasterEric/jsonpatch/:f9b83215acd586dc28754b4ae7f69d4c06c3b4d3
- jsonpath git(https://github.com/EliteMasterEric/jsonpath/:7a24193717b36393458c15c0435bb7c4470ecdda
- lime git(https://github.com/FunkinCrew/lime/:fe3368f611a84a19afc03011353945ae4da8fffd
- mconsole git(https://github.com/massive-oss/mconsole/:06c0499ed8f80628a0e6e55ffa32c3cbd688a838
- mcover git(https://github.com/massive-oss/mcover/src:c3c47cd682b0b202a41caee95321989391b617ef
- mockatoo git(https://github.com/FunkinCrew/mockatoo/src:13d77a0a8eaf5e789ef5dae6cd33eee812deda36
- munit git(https://github.com/FunkinCrew/MassiveUnit/src:f61be7f7ba796595f45023ca65164a485aba0e7e
- openfl git(https://github.com/FunkinCrew/openfl/:8306425c497766739510ab29e876059c96f77bd2
- polymod git(https://github.com/larsiusprime/polymod/:0fbdf27fe124549730accd540cec8a183f8652c0
- thx.core git(https://github.com/fponticelli/thx.core/:76d87418fadd92eb8e1b61f004cff27d656e53dd
- thx.semver git(https://github.com/fponticelli/thx.semver/:bdb191fe7cf745c02a980749906dbf22719e200b

=====================

Loaded mods: 
No mods loaded.

=====================

RangeError
  in funkin/vis/dsp/SpectralAnalyzer.hx#198
  in funkin/audio/visualize/ABotVis.hx#98
  in funkin/audio/visualize/ABotVis.hx#89
  in flixel/group/FlxGroup.hx#180
  in flixel/group/FlxSpriteGroup.hx#233
  in funkin/play/stage/Stage.hx#811
  in polymod/hscript/_internal/HScriptedClassMacro.hx#870
  in C:\actions-runner\_work\_tool\haxe\4.3.4\x64\std/cpp/_std/Reflect.hx#63
  in polymod/hscript/_internal/PolymodScriptClass.hx#553
  in polymod/hscript/_internal/HScriptedClassMacro.hx#837
  in flixel/group/FlxGroup.hx#180
  in flixel/FlxState.hx#109
  in flixel/FlxSubState.hx#80
  in funkin/play/PlayState.hx#778
  in flixel/FlxGame.hx#882
  in flixel/FlxGame.hx#567

**Comment by Hundrec** [comment] 2024-10-07 15:25
This issue is a duplicate of the following:
1. https://github.com/FunkinCrew/Funkin/issues/3487
2. https://github.com/FunkinCrew/Funkin/issues/3495
3. https://github.com/FunkinCrew/Funkin/issues/3499

Please close this issue using the purple checkmark button.

**Closed** 2024-10-13 14:25 UTC
Labels: status: duplicate
