### ISSUE TITLE
Bug Report: Mouse visible outside of the editors

### ISSUE THREAD

**Issue by sphis-Sinco** [FunkinCrew/Funkin#3879] opened 2024-11-19 19:59 UTC
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

0.5.3

### Description (include any images, videos, errors, or crash logs)

I opened the game and went to play some Erect/Nightmare songs and after a bit I just realized the mouse is visible outside of the editors and yeah that's a bug so I am reporting this here.

![screenshot-2024-11-19-13-57-45](https://github.com/user-attachments/assets/9aa51208-2033-4c72-88b7-770ef12acb6c)
![screenshot-2024-11-19-13-57-38](https://github.com/user-attachments/assets/3013d228-d336-48c0-a717-a5ee7644465f)
![screenshot-2024-11-19-13-57-25](https://github.com/user-attachments/assets/fe648a56-bb14-48c5-80be-3fc704cec816)
![screenshot-2024-11-19-13-57-22](https://github.com/user-attachments/assets/2f8eb7de-848a-4706-bb11-dae92c466182)
![screenshot-2024-11-19-13-54-38](https://github.com/user-attachments/assets/871d636b-c63a-4e46-9e24-d24f2b72d76b)

**Comment by Hundrec** [comment] 2024-11-19 20:07
I believe this is a duplicate of https://github.com/FunkinCrew/Funkin/issues/3712

**Comment by sphis-Sinco** [comment] 2024-11-19 20:13
ok

**Closed** 2024-11-19 20:13 UTC
Labels: status: duplicate
