### ISSUE TITLE
Bug Report: dadbattle pico mix

### ISSUE THREAD

**Issue by picoburpsalot** [FunkinCrew/Funkin#3223] opened 2024-09-13 21:13 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Itch.io (Downloadable Build) - Windows

### If you are playing on a browser, which one are you using?

None

### Version

latest version

**Comment by picoburpsalot** [comment] 2024-09-13 21:14
its my first time reporting a bug sorry i messed it up a bit but when i play dadbattle the song plays but no notes appear and pico and dad dont sing

**Comment by Hundrec** [comment] 2024-09-14 07:01
Sounds like the same issue as #3225

**Comment by NotHyper-474** [comment] 2024-09-14 10:36
> Sounds like the same issue as #3225 
> 
> Edit: Yep, just saw your comment on it. You can close this issue now :)

Actually both are duplicates of https://github.com/FunkinCrew/Funkin/issues/3188

**Comment by EliteMasterEric** [comment] 2024-09-16 20:36
Closing since this is a duplicate of #3149

**Closed by EliteMasterEric** 2024-09-16 20:36 UTC
Labels: status: duplicate
