### ISSUE TITLE
Enhancement: Freeplay Boyfriend Bops To Song BPM

### ISSUE THREAD

**Issue by ChickenSwimmer2020** [FunkinCrew/Funkin#3632] opened 2024-10-10 14:23 UTC
### Issue Checklist

- [X] I have properly named my enhancement
- [X] I have checked the Issues/Discussions pages to see if my enhancement has already been suggested

### What is your suggestion, and why should it be implemented?

on the Freeplay menu, boyfriend should bop his head to the current song BPM, not really sure if i need to explain any further as its kind of a simple idea.

why i feel it should be implemented: i think it would look cool if they bopped on beat like girlfriend on the title screen

**Comment by NotHyper-474** [comment] 2024-10-10 14:26
Duplicate of #2760

**Comment by ChickenSwimmer2020** [comment] 2024-10-10 14:29
i literally searched up bpm under enhancements, how did i not see that. I'm stupid 🤦

**Comment by NotHyper-474** [comment] 2024-10-10 15:06
That's fine. Now please click on the arrow by the Close Issue button next to the Comment button and then on "Close as not planned"

![Screenshot_20241010-120447_Chrome.jpg](https://github.com/user-attachments/assets/d0ef4ef4-a534-4fc0-bd4a-c624a3c50bb2)

**Closed** 2024-10-10 15:07 UTC
Labels: status: duplicate
