### ISSUE TITLE
General graphics inconsistencies

### ISSUE THREAD

**Issue by NovaSoup** [FunkinCrew/Funkin#329] opened 2021-02-03 00:25 UTC
This is kinda a bug report but not really so i just made it blank.
For clarification: These are ongoing inconsistencies, not just bugs that happen randomly. More of a design fix then a bug fix.

1. Bopping to the music
So basically, characters in different songs and weeks will bop to different rhythms randomly. For example, in Week 1 the dad will seemingly bop to his own rhythm, not even matching the song while the boyfriend is matching it. Week 2 seems fine, but i havent checked too much. Week 3, Pico has the same issue of bopping not to the rhythm of the music. Week 4, however, the mom will sometimes bop every 1st and 3rd beat, while the Boyfriend will bop every 2nd and 4th. Although in a few they match up. Week 5 is perfect, and i havent played Week 6 enough to check. I say you make every character who is singing bop to the music every 2nd and 4th beat of the song no matter what.

2. Arrow positions
The gray arrows that stay at the top of the screen are slightly to the right of the screen and not centered.

3. Long arrows
The bottom end of a long arrow you have to hold is disconnected from the 'holding' part.

4. Sprites when choosing a week
When on the story mode screen, the enemy sprites will be in seemingly random positions and have weird sizes. For example Pico will be in the top left corner or the mom and dad from Week 5 will be tiny.

5. The 'C' in the freeplay select
The letter 'C' (for example when looking at PICO in the freeplay gui) will wobble faster than any of the other letters.

EDIT: 6. Dad in week selection
When hovering over the tutorial in Story Mode, you should remove the dad that is shown in the sprite areaa

Thats all i know of.
...is this too nitpicky?

**Comment by regulad** [comment] 2021-02-03 01:33
2. is a duplicate of #223, and I could've sworn 3. is caused by the charting editor since newer songs don't have the issue

**Comment by Templarfreak** [comment] 2021-02-03 06:51
Cannot reproduce 4 with the exception of tiny mom & dad for Week 5. They are kinda tiny, but they're _consistently_ tiny.
For 5, C does seem to move more but I can't tell if it's really faster or if there is just a bigger difference between the frames for C as opposed to most other letters.

**Comment by NovaSoup** [comment] 2021-02-03 11:46
> Cannot reproduce 4 with the exception of tiny mom & dad for Week 5. They are kinda tiny, but they're _consistently_ tiny.

Hmm. They must've fixed number 4 in the week 6 update.

**Comment by ActualMandM** [comment] 2021-02-03 18:29
> I could've sworn 3. is caused by the charting editor since newer songs don't have the issue

It happens in Thorns

<details><summary>Week 6 spoilers</summary>
<p>

<img width="641" alt="2021-02-03_10-28-57_Funkin" src="https://user-images.githubusercontent.com/15317421/106792227-bce89f80-660a-11eb-9840-fb7d202a3ee9.png">

</p>
</details>

**Closed** 2024-05-08 07:06 UTC
Labels: legacy
