### ISSUE TITLE
Bug Report: No charting on DadBattle (Pico Mix) in Free Play

### ISSUE THREAD

**Issue by RevenantOfSin** [FunkinCrew/Funkin#3405] opened 2024-09-21 05:55 UTC
### Issue Checklist

- [ ] I have properly named the issue
- [ ] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Microsoft Edge

### Version

pico mix free play update

### Context (Provide images, videos, etc.)

When selecting DadBattle (Pico Mix) on free play, no notes show up on screen, leaving you to sit there for the entire song. Results screen also deem it a 0% accuracy/loss.

**Comment by Hundrec** [comment] 2024-09-21 06:26
Dadbattle (Pico Mix) is currently only charted for Hard mode.
This issue was reported here: https://github.com/FunkinCrew/Funkin/issues/3149

**Comment by EliteMasterEric** [comment] 2024-09-21 09:35
Duplicate of #3149

**Closed by EliteMasterEric** 2024-09-21 09:35 UTC
Labels: status: duplicate
