### ISSUE TITLE
Bug Report: I cannot play the new Christmas songs due to lag

### ISSUE THREAD

**Issue by nothatguy64** [FunkinCrew/Funkin#3404] opened 2024-09-21 04:26 UTC
### Issue Checklist

- [X] I have properly named the issue
- [X] I have checked the issues/discussions pages to see if the issue has been previously reported

### What platform are you using?

Newgrounds (Web)

### If you are playing on a browser, which one are you using?

Google Chrome

### Version

0.5.0

### Context (Provide images, videos, etc.)

I am trying to play the christmas songs, but they lag soooo much to the point where I get blueballed due to sheer lag. Sometimes this crashes the game. Other songs lag somewhat, but are playable which is why I never complained until now.

### Steps to reproduce (or crash logs, errors, etc.)

Maybe try reducing the load of the game, or making things one layer only. I'm not sure how the backgrounds work, but judging that the christmas week has a lot of issues, I'm assuming it's because there is a lot of elements.

**Comment by Hundrec** [comment] 2024-09-21 05:33
Here's some information regarding lag spikes in the new Week 5 stage: https://github.com/FunkinCrew/Funkin/issues/3161

**Comment by EliteMasterEric** [comment] 2024-09-22 04:49
I would say this is a duplicate of #3161 and provides no additional information so I'm closing it.

**Closed by EliteMasterEric** 2024-09-22 04:49 UTC
Labels: status: duplicate
