### ISSUE TITLE
Can't compile game

### ISSUE THREAD

**Issue by REEEmonke** [FunkinCrew/Funkin#1017] opened 2021-05-04 03:53 UTC
When I run the command to compile the game, it says:
source/Discord.hx:4: characters 8-30 : Type not found : discord_rpc.DiscordRpc
source/Discord.hx:13: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:23: characters 4-14 : Type not found : DiscordRpc
source/Discord.hx:28: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:33: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:38: characters 3-13 : Type not found : DiscordRpc
source/Discord.hx:74: characters 3-13 : Type not found : DiscordRpc
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access

Why? can somebody help?

**Comment by OPNA2608** [comment] 2021-05-04 09:46
Duplicate of #678.

**Closed** 2024-05-08 07:00 UTC
Labels: legacy
